query getOneUser($userId: uuid!) {
  user(id: $userId) {
    id
    displayName
    avatarUrl
    workspaceMembers {
      id
      userId
      workspaceId
      type
      workspace {
        creatorUserId
        id
        slug
        name
        apps {
          ...Project
        }
      }
    }
  }
}
