import type {
  DashboardLayout,
  DashboardTemplate,
} from '@/features/orgs/projects/overview/dashboard/types';

export const DEFAULT_LAYOUT: DashboardLayout = [
  {
    i: 'm-rps',
    type: 'metric',
    cfg: { metric: 'rps', window: '5m' },
    x: 0,
    y: 0,
    w: 3,
    h: 3,
    minW: 2,
    minH: 2,
  },
  {
    i: 'm-dau',
    type: 'metric',
    cfg: { metric: 'dau', window: '24h' },
    x: 3,
    y: 0,
    w: 3,
    h: 3,
    minW: 2,
    minH: 2,
  },
  {
    i: 'm-reqs',
    type: 'metric',
    cfg: { metric: 'reqs', window: 'MTD' },
    x: 6,
    y: 0,
    w: 3,
    h: 3,
    minW: 2,
    minH: 2,
  },
  {
    i: 'm-store',
    type: 'metric',
    cfg: { metric: 'storage' },
    x: 9,
    y: 0,
    w: 3,
    h: 3,
    minW: 2,
    minH: 2,
  },
  {
    i: 'pulse',
    type: 'pulse',
    cfg: {},
    x: 0,
    y: 3,
    w: 8,
    h: 5,
    minW: 5,
    minH: 4,
  },
  {
    i: 'health',
    type: 'health',
    cfg: {},
    x: 8,
    y: 3,
    w: 4,
    h: 8,
    minW: 3,
    minH: 4,
  },
  {
    i: 'deploys',
    type: 'deploys',
    cfg: { count: 5 },
    x: 0,
    y: 8,
    w: 8,
    h: 5,
    minW: 4,
    minH: 4,
  },
  {
    i: 'info',
    type: 'info',
    cfg: {},
    x: 8,
    y: 11,
    w: 4,
    h: 5,
    minW: 3,
    minH: 4,
  },
  {
    i: 'logs',
    type: 'logs',
    cfg: { count: 7 },
    x: 0,
    y: 13,
    w: 8,
    h: 5,
    minW: 4,
    minH: 4,
  },
  {
    i: 'repo',
    type: 'repo',
    cfg: {},
    x: 8,
    y: 16,
    w: 4,
    h: 4,
    minW: 3,
    minH: 3,
  },
  {
    i: 'docs',
    type: 'docs',
    cfg: { variant: 'frameworks' },
    x: 0,
    y: 18,
    w: 8,
    h: 5,
    minW: 4,
    minH: 4,
  },
];

export const COMPACT_LAYOUT: DashboardLayout = [
  {
    i: 'm-rps',
    type: 'metric',
    cfg: { metric: 'rps', window: '5m' },
    x: 0,
    y: 0,
    w: 3,
    h: 2,
    minW: 2,
    minH: 2,
  },
  {
    i: 'm-dau',
    type: 'metric',
    cfg: { metric: 'dau', window: '24h' },
    x: 3,
    y: 0,
    w: 3,
    h: 2,
    minW: 2,
    minH: 2,
  },
  {
    i: 'm-reqs',
    type: 'metric',
    cfg: { metric: 'reqs', window: 'MTD' },
    x: 6,
    y: 0,
    w: 3,
    h: 2,
    minW: 2,
    minH: 2,
  },
  {
    i: 'm-store',
    type: 'metric',
    cfg: { metric: 'storage' },
    x: 9,
    y: 0,
    w: 3,
    h: 2,
    minW: 2,
    minH: 2,
  },
  {
    i: 'pulse',
    type: 'pulse',
    cfg: {},
    x: 0,
    y: 2,
    w: 12,
    h: 4,
    minW: 5,
    minH: 4,
  },
  {
    i: 'health',
    type: 'health',
    cfg: {},
    x: 0,
    y: 6,
    w: 4,
    h: 5,
    minW: 3,
    minH: 4,
  },
  {
    i: 'deploys',
    type: 'deploys',
    cfg: { count: 4 },
    x: 4,
    y: 6,
    w: 4,
    h: 5,
    minW: 4,
    minH: 4,
  },
  {
    i: 'logs',
    type: 'logs',
    cfg: { count: 5 },
    x: 8,
    y: 6,
    w: 4,
    h: 5,
    minW: 4,
    minH: 4,
  },
  {
    i: 'info',
    type: 'info',
    cfg: {},
    x: 0,
    y: 11,
    w: 6,
    h: 4,
    minW: 3,
    minH: 4,
  },
  {
    i: 'repo',
    type: 'repo',
    cfg: {},
    x: 6,
    y: 11,
    w: 6,
    h: 4,
    minW: 3,
    minH: 3,
  },
];

export const TEMPLATES: DashboardTemplate[] = [
  {
    id: 'default',
    name: 'Default',
    desc: 'The full Nhost overview — metric cards, live pulse, deploys, logs, and docs.',
    layout: DEFAULT_LAYOUT,
  },
  {
    id: 'compact',
    name: 'Compact',
    desc: 'Tighter spacing for smaller screens — slimmer metrics, three-column ops row, no docs.',
    layout: COMPACT_LAYOUT,
  },
];

export const GRID_COLS = 12;
export const GRID_ROW_HEIGHT = 64;
export const GRID_GUTTER = 12;

export function findMatchingTemplateId(
  current: DashboardLayout,
  templates: DashboardTemplate[] = TEMPLATES,
): string {
  const sig = (l: DashboardLayout) =>
    l
      .map((it) => `${it.i}:${it.x},${it.y},${it.w},${it.h}`)
      .sort()
      .join('|');
  return templates.find((t) => sig(t.layout) === sig(current))?.id ?? 'default';
}
