# This file is auto-generated by tools/codegen. Do not edit manually.
from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, Literal

import httpx
from pydantic import BaseModel, ConfigDict, Field

from ..fetch import (
    ChainFunction,
    FetchResponse,
    HTTPError,
    create_enhanced_fetch,
    decode_json,
    to_json,
    to_jsonable,
)

_MIN_ERROR_STATUS = 400


OAuth2RevokeRequestToken_type_hint = Literal["access_token", "refresh_token"]

class OAuth2RevokeRequest(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")

    token: str = Field(repr=False)
    token_type_hint: OAuth2RevokeRequestToken_type_hint | None = Field(
        default=None,
        description="Optional token type hint declared nullable in OpenAPI.",
    )
    client_id: str | None = Field(
        default=None,
        description="Optional client identifier declared nullable in OpenAPI.",
    )
    client_secret: str | None = Field(
        default=None,
        repr=False,
        description="Optional client secret declared nullable in OpenAPI.",
    )

class OAuth2ErrorResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")

    error: str = Field(
        description="OAuth2 error code",
    )
    error_description: str | None = Field(
        default=None,
        description="Human-readable error description",
    )


class Client:
    """Generated async API client backed by an httpx.AsyncClient and a middleware chain."""

    def __init__(
        self,
        base_url: str,
        *,
        chain_functions: Sequence[ChainFunction] = (),
        http_client: httpx.AsyncClient | None = None,
    ) -> None:
        self.base_url = base_url
        self._chain_functions = list(chain_functions)
        self._owns_http_client = http_client is None
        self._http = http_client if http_client is not None else httpx.AsyncClient()
        self._fetch = create_enhanced_fetch(self._http, self._chain_functions)

    async def __aenter__(self) -> Client:
        return self

    async def __aexit__(self, *_: object) -> None:
        await self.aclose()

    async def aclose(self) -> None:
        """Close the internally owned HTTP client, if any."""
        if self._owns_http_client:
            await self._http.aclose()

    def push_chain_function(self, chain_function: ChainFunction) -> None:
        """Append a middleware chain function and rebuild the fetch pipeline."""
        self._chain_functions.append(chain_function)
        self._fetch = create_enhanced_fetch(self._http, self._chain_functions)


    async def oauth2_revoke(
        self,
        *,
        body: OAuth2RevokeRequest,
        headers: Mapping[str, str] | None = None,
    ) -> FetchResponse[None]:
        (
            """OAuth2 Token Revocation (RFC 7009)\n\nRevoke an access token or refresh token.\n\n"""
            """Args:\n    body (OAuth2RevokeRequest): Request body.\n    headers (Mapping[str, """
            """str] | None): Additional request headers.\n\nReturns:\n    FetchResponse[None]: """
            """The HTTP response."""
        )
        url = f"{self.base_url}/oauth2/revoke"
        query = None
        request = self._http.build_request(
            "POST",
            url,
            params=query,
            data=to_jsonable(body),
            headers=headers,
        )
        response = await self._fetch(request)
        if response.status_code >= _MIN_ERROR_STATUS:
            raise HTTPError.from_response(response)
        payload = None
        return FetchResponse(body=payload, status=response.status_code, headers=response.headers)


def create_api_client(
    base_url: str,
    *,
    chain_functions: Sequence[ChainFunction] = (),
    http_client: httpx.AsyncClient | None = None,
) -> Client:
    """Create a generated API client."""
    return Client(base_url, chain_functions=chain_functions, http_client=http_client)

__all__ = [
    "OAuth2RevokeRequestToken_type_hint",
    "OAuth2RevokeRequest",
    "OAuth2ErrorResponse",
    "Client",
    "create_api_client",
]
