// import { Notifications } from '@mantine/notifications'
// import { urlFromSubdomain } from '@nhost/nhost-js'
// import { NhostProvider } from '@nhost/react'
// import { NhostClient } from '@nhost/nextjs'
// import { NhostApolloProvider } from '@nhost/react-apollo'
import { inspect } from '@xstate/inspect'
// import NavBar from '../components/NavBar'
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@mantine/core/styles.css';
import { ColorSchemeScript, mantineHtmlProps, MantineProvider } from '@mantine/core';
import { theme } from '../theme';
import * as React from 'react'

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const devTools = typeof window !== 'undefined' && !!process.env.NEXT_PUBLIC_DEBUG
if (devTools) {
  inspect({
    url: 'https://stately.ai/viz?inspect',
    iframe: false
  })
}

// const nhost = new NhostClient({ subdomain: 'local', devTools })
const title = 'Nhost with NextJs'

export const metadata: Metadata = {
  title,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body>
        {/* <NhostProvider nhost={nhost}> */}
        {/*   <NhostApolloProvider nhost={nhost}> */}

        <MantineProvider theme={theme}>
          {/* <Notifications /> */}
          {/* <AppShell */}
          {/*   padding="md" */}
          {/* // navbar={<NavBar />} */}
          {/* // header={ */}
          {/* //   <Header height={60} p="xs"> */}
          {/* //     {title} */}
          {/* //   </Header> */}
          {/* // } */}
          {/* > */}
          {children}
          {/* </AppShell> */}
        </MantineProvider>
        {/*   </NhostApolloProvider> */}
        {/* </NhostProvider> */}
      </body>
    </html>
  );
}
