name: 'Check PR Authorization'
description: 'Check if the workflow should run based on author/commenter authorization and get PR details'

outputs:
  should_run:
    description: 'Whether the workflow should run (true/false)'
    value: ${{ steps.check.outputs.should_run }}
  sha:
    description: 'The SHA to checkout'
    value: ${{ steps.pr.outputs.sha }}

runs:
  using: 'composite'
  steps:
    - name: Check authorization
      id: check
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          echo "should_run=true" >> $GITHUB_OUTPUT
        elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
          if [[ "${{ contains(fromJson('["OWNER", "MEMBER"]'), github.event.pull_request.author_association) }}" == "true" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi
        elif [[ "${{ github.event_name }}" == "issue_comment" ]]; then
          if [[ "${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/ok-to-test') && contains(fromJson('["OWNER", "MEMBER"]'), github.event.comment.author_association) }}" == "true" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "should_run=false" >> $GITHUB_OUTPUT
        fi

    - name: Get PR SHA
      id: pr
      if: steps.check.outputs.should_run == 'true'
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT
        elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
        elif [[ "${{ github.event_name }}" == "issue_comment" ]]; then
          echo "sha=refs/pull/${{ github.event.issue.number }}/head" >> $GITHUB_OUTPUT
        fi
