query getOrganizations($userId: uuid!) {
  organizations(
    order_by: { name: asc }
    where: { members: { userID: { _eq: $userId } } }
  ) {
    id
    name
    slug
    plan {
      id
      name
      price
      deprecated
      individual
      isFree
      featureMaxDbSize
      slaLevel
    }
    apps(order_by: { name: asc }) {
      id
      slug
      name
      repositoryProductionBranch
      subdomain
      createdAt
      desiredState
      nhostBaseFolder
      automaticDeploys
      featureFlags {
        description
        id
        name
        value
      }
      appStates(order_by: { createdAt: desc }, limit: 1) {
        id
        appId
        message
        stateId
        createdAt
      }
      region {
        id
        countryCode
        name
        domain
        city
      }
      legacyPlan {
        id
        name
        price
        isFree
        featureMaxDbSize
      }
      githubRepository {
        fullName
      }
      deployments(limit: 4, order_by: { deploymentStartedAt: desc }) {
        id
        commitSHA
        commitMessage
        commitUserName
        deploymentStartedAt
        deploymentEndedAt
        commitUserAvatarUrl
        deploymentStatus
      }
      pipelineRuns(limit: 4, order_by: { startedAt: desc }) {
        id
        name
        startedAt
        endedAt
        status
        input
        appId
        createdAt
      }
      creator {
        id
        email
        displayName
      }
    }
    members {
      id
      role
      user {
        id
        email
        displayName
        avatarUrl
      }
    }
  }
}
