query getOrganizationInvites($organizationId: uuid!) {
  organizationMemberInvites(
    where: { organizationID: { _eq: $organizationId } }
    order_by: { createdAt: desc }
  ) {
    id
    email
    role
    createdAt
    updateAt
  }
}
