query getOrganizations($userId: uuid!) {
  organizations(
    order_by: { name: asc }
    where: { members: { userID: { _eq: $userId } } }
  ) {
    id
    name
    slug
    plan {
      id
      name
      deprecated
      individual
      isFree
      featureMaxDbSize
    }
    apps(order_by: { name: asc }) {
      id
      name
      subdomain
      slug
    }
  }
}
