query getOrganization($orgSlug: String!) {
  organizations(where: { slug: { _eq: $orgSlug } }) {
    id
    name
    slug
    plan {
      id
      name
      deprecated
      individual
      isFree
    }
    members {
      id
      role
      user {
        id
      }
    }
    apps(order_by: { name: asc }) {
      id
      name
      subdomain
      slug
    }
  }
}
