query getProjects($orgSlug: String!) {
  apps(where: { organization: { slug: { _eq: $orgSlug } } }) {
    id
    name
    slug
    createdAt
    subdomain
    region {
      id
      name
    }
    deployments(limit: 4, order_by: { deploymentStartedAt: desc }) {
      id
      commitSHA
      commitMessage
      commitUserName
      deploymentStartedAt
      deploymentEndedAt
      commitUserAvatarUrl
      deploymentStatus
    }
    creator {
      id
      email
      displayName
    }
    appStates(order_by: { createdAt: desc }, limit: 1) {
      id
      appId
      message
      stateId
      createdAt
    }
  }
}
