query getProjectState($subdomain: String!) {
  apps(where: { subdomain: { _eq: $subdomain } }) {
    id
    name
    subdomain
    createdAt
    desiredState
    appStates(order_by: { createdAt: desc }, limit: 1) {
      id
      appId
      message
      stateId
      createdAt
    }
  }
}
