dashboard:
  - any:
      - changed-files:
          - any-glob-to-any-file: ['dashboard/**/*']

documentation:
  - any: ['docs/**/*']

examples:
  - any: ['examples/**/*']

sdk:
  - any: ['packages/**/*']

integrations:
  - any: ['integrations/**/*']

react:
  - any: ['{packages,examples,integrations}/*react*/**/*']

nextjs:
  - any: ['{packages,examples}/*next*/**/*']

vue:
  - any: ['{packages,examples,integrations}/*vue*/**/*']
