dashboard:
  - dashboard/**/*

# Add 'label2' to any file changes within 'example2' folder
documentation:
  - any:
      - docs/**/*
      - '!docs/docs/reference/docgen/**/*'
  - examples/**/*

sdk:
  - packages/**/*

react:
  - '{packages,examples}/*react*/**/*'

nextjs:
  - '{packages,examples}/*next*/**/*'

vue:
  - '{packages,examples}/*vue*/**/*'
