# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "templates/**"
      - "examples/**"
      - "assets/**"
      - "**.md"
      - "LICENSE"
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "templates/**"
      - "examples/**"
      - "assets/**"
      - "**.md"
      - "LICENSE"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.30.1
          run_install: true

      - name: Cache turbo
        uses: actions/cache@v2
        with:
          path: ./node_modules/.cache
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}

      - run: pnpm run ci
