packages:
  - 'packages/**'
  - 'integrations/**'
  - 'dashboard'
  - 'docs'
  - '!**/test/**'
  - '!out/**'
  - 'examples/**'
  - 'templates/**'
  - '!templates/cra-template-nhost-react-apollo-template/**'
  - '!templates/react-native/**'
  - 'examples/quickstarts/*'
  - '!**/functions'
