packages:
  - dashboard
  - docs
  - packages/**
  - examples/demos/**
  - examples/guides/**
  - examples/quickstarts/**
  - examples/tutorials/**
  - '!**/test/**'
  - '!out/**'
  - '!**/functions'
