export * from './ClassTemplate'
export { default as ClassTemplate } from './ClassTemplate'
export * from './FunctionTemplate'
export { default as FunctionTemplate } from './FunctionTemplate'
export * from './TypeTemplate'
export { default as TypeTemplate } from './TypeTemplate'
