CREATE SCHEMA cf_insert_order;
CREATE TABLE cf_insert_order.events (
    seq bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag text NOT NULL
);
CREATE TABLE cf_insert_order.before_object (
    id integer PRIMARY KEY,
    tag text NOT NULL
);
CREATE TABLE cf_insert_order.parent (
    id integer PRIMARY KEY,
    label text NOT NULL,
    before_id integer REFERENCES cf_insert_order.before_object(id)
);
CREATE TABLE cf_insert_order.child (
    id integer PRIMARY KEY,
    tag text NOT NULL,
    parent_id integer NOT NULL REFERENCES cf_insert_order.parent(id)
);
CREATE TABLE cf_insert_order.after_0 (
    id integer PRIMARY KEY,
    tag text NOT NULL,
    parent_id integer NOT NULL UNIQUE REFERENCES cf_insert_order.parent(id)
);
CREATE TABLE cf_insert_order.after_1 (
    id integer PRIMARY KEY,
    tag text NOT NULL,
    parent_id integer NOT NULL UNIQUE REFERENCES cf_insert_order.parent(id)
);
CREATE FUNCTION cf_insert_order.log_insert() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO cf_insert_order.events(tag) VALUES(NEW.tag);
    RETURN NEW;
END $$;
CREATE TRIGGER log_before AFTER INSERT ON cf_insert_order.before_object
    FOR EACH ROW EXECUTE FUNCTION cf_insert_order.log_insert();
CREATE TRIGGER log_child AFTER INSERT ON cf_insert_order.child
    FOR EACH ROW EXECUTE FUNCTION cf_insert_order.log_insert();
CREATE TRIGGER log_after_0 AFTER INSERT ON cf_insert_order.after_0
    FOR EACH ROW EXECUTE FUNCTION cf_insert_order.log_insert();
CREATE TRIGGER log_after_1 AFTER INSERT ON cf_insert_order.after_1
    FOR EACH ROW EXECUTE FUNCTION cf_insert_order.log_insert();
-- Parent uses label rather than tag so the plain-column permission below can
-- reject a later input row based on the prior root's label.
CREATE FUNCTION cf_insert_order.log_parent() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO cf_insert_order.events(tag) VALUES(NEW.label);
    RETURN NEW;
END $$;
CREATE TRIGGER log_parent AFTER INSERT ON cf_insert_order.parent
    FOR EACH ROW EXECUTE FUNCTION cf_insert_order.log_parent();
