-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE categories (
--   value text PRIMARY KEY,
--   comment text
-- );
--
-- INSERT INTO categories (value, comment) VALUES
--   ('novel', 'Novels'),
--   ('essay', 'whatev');
