# This file is auto-generated by tools/codegen. Do not edit manually.
# ruff: noqa
# mypy: ignore-errors
from __future__ import annotations

import json
from typing import Any, Literal
from urllib.parse import quote

import httpx
from pydantic import BaseModel, ConfigDict, Field

from ..fetch import (
    ChainFunction,
    FetchError,
    FetchResponse,
    UploadFile,
    create_enhanced_fetch,
    decode_json,
    to_file_part,
    to_json,
    to_jsonable,
)


def _escape_path(value: object) -> str:
    segment = str(value)
    if segment == ".":
        return "%2E"
    if segment == "..":
        return "%2E%2E"
    return quote(segment, safe="")


def _parameter_scalar(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (dict, list)):
        return json.dumps(value, separators=(",", ":"))
    return str(value)


def _query_parameter(name: str, value: Any, style: str, explode: bool) -> list[tuple[str, str]]:
    value = to_jsonable(value)
    if isinstance(value, list):
        if explode:
            return [(name, _parameter_scalar(item)) for item in value]
        return [(name, ",".join(_parameter_scalar(item) for item in value))]
    if isinstance(value, dict):
        if style == "deepObject":
            return [(f"{name}[{key}]", _parameter_scalar(item)) for key, item in value.items()]
        if explode:
            return [(key, _parameter_scalar(item)) for key, item in value.items()]
        parts = [part for key, item in value.items() for part in (key, _parameter_scalar(item))]
        return [(name, ",".join(parts))]
    return [(name, _parameter_scalar(value))]


def _header_value(value: Any, explode: bool) -> str:
    value = to_jsonable(value)
    if isinstance(value, list):
        return ",".join(_parameter_scalar(item) for item in value)
    if isinstance(value, dict):
        parts: list[str] = []
        for key, item in value.items():
            if explode:
                parts.append(f"{key}={_parameter_scalar(item)}")
            else:
                parts.extend((key, _parameter_scalar(item)))
        return ",".join(parts)
    return _parameter_scalar(value)


RFC2822Date = str


class ErrorResponseError(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    message: str
    data: dict[str, Any] | None = None


class ErrorResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    error: ErrorResponseError | None = None


class ErrorResponseWithProcessedFilesError(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    message: str
    data: dict[str, Any] | None = None


class ErrorResponseWithProcessedFiles(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    processed_files: list[FileMetadata] | None = Field(default=None, alias="processedFiles")
    error: ErrorResponseWithProcessedFilesError | None = None


class FileMetadata(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    name: str
    size: int
    bucket_id: str = Field(alias="bucketId")
    etag: str
    created_at: str = Field(alias="createdAt")
    updated_at: str = Field(alias="updatedAt")
    is_uploaded: bool = Field(alias="isUploaded")
    mime_type: str = Field(alias="mimeType")
    uploaded_by_user_id: str | None = Field(default=None, alias="uploadedByUserId")
    metadata: dict[str, Any] | None = None


class FileSummary(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    name: str
    bucket_id: str = Field(alias="bucketId")
    is_uploaded: bool = Field(alias="isUploaded")


class PresignedURLResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    url: str = Field(repr=False)
    expiration: int


class UpdateFileMetadata(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    name: str | None = None
    metadata: dict[str, Any] | None = None


class UploadFileMetadata(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str | None = None
    name: str | None = None
    metadata: dict[str, Any] | None = None


class VersionInformation(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    build_version: str = Field(alias="buildVersion")


OutputImageFormat = Literal["auto", "same", "jpeg", "webp", "png", "avif", "heic"]


class UploadFilesBody(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    bucket_id: str | None = Field(default=None, alias="bucket-id")
    metadata: list[UploadFileMetadata] | None = Field(default=None, alias="metadata[]")
    file: list[bytes | UploadFile] = Field(alias="file[]")


class UploadFilesResponse201(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    processed_files: list[FileMetadata] = Field(alias="processedFiles")


class ReplaceFileBody(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    metadata: UpdateFileMetadata | None = None
    file: bytes | UploadFile | None = None


class DeleteBrokenMetadataResponse200(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    metadata: list[FileSummary] | None = None


class DeleteOrphanedFilesResponse200(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    files: list[str] | None = None


class ListBrokenMetadataResponse200(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    metadata: list[FileSummary] | None = None


class ListFilesNotUploadedResponse200(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    metadata: list[FileSummary] | None = None


class ListOrphanedFilesResponse200(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    files: list[str] | None = None


class GetFileParams(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    q: int | None = None
    h: int | None = None
    w: int | None = None
    b: float | None = None
    f: OutputImageFormat | None = None

    if_match: str | None = Field(default=None, alias="if-match")
    if_none_match: str | None = Field(default=None, alias="if-none-match")
    if_modified_since: str | None = Field(default=None, alias="if-modified-since")
    if_unmodified_since: str | None = Field(default=None, alias="if-unmodified-since")
    range: str | None = Field(default=None, alias="Range")


class GetFileMetadataHeadersParams(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    q: int | None = None
    h: int | None = None
    w: int | None = None
    b: float | None = None
    f: OutputImageFormat | None = None

    if_match: str | None = Field(default=None, alias="if-match")
    if_none_match: str | None = Field(default=None, alias="if-none-match")
    if_modified_since: str | None = Field(default=None, alias="if-modified-since")
    if_unmodified_since: str | None = Field(default=None, alias="if-unmodified-since")


class Client:
    """Generated async API client backed by an httpx.AsyncClient and a middleware chain."""

    def __init__(
        self,
        base_url: str,
        chain_functions: list[ChainFunction] | None = None,
        http_client: httpx.AsyncClient | None = None,
    ) -> None:
        self.base_url = base_url
        self._chain_functions: list[ChainFunction] = list(chain_functions or [])
        self._http = http_client if http_client is not None else httpx.AsyncClient()
        self._fetch = create_enhanced_fetch(self._http, self._chain_functions)

    def push_chain_function(self, chain_function: ChainFunction) -> None:
        """Append a middleware chain function and rebuild the fetch pipeline."""
        self._chain_functions.append(chain_function)
        self._fetch = create_enhanced_fetch(self._http, self._chain_functions)

    async def upload_files(
        self,
        body: UploadFilesBody,
        headers: dict[str, str] | None = None,
    ) -> FetchResponse[UploadFilesResponse201]:
        url = f"{self.base_url}/files"
        query = None
        _data: dict[str, Any] = {}
        _files: list[tuple[str, Any]] = []
        if body.bucket_id is not None:
            _data["bucket-id"] = body.bucket_id
        if body.metadata is not None:
            for _item in body.metadata:
                _files.append(("metadata[]", (None, to_json(_item), "application/json")))
        if body.file is not None:
            for _item in body.file:
                _files.append(("file[]", to_file_part(_item)))
        request = self._http.build_request(
            "POST",
            url,
            params=query,
            data=_data or None,
            files=_files or None,
            headers=headers,
        )
        response = await self._fetch(request)
        if response.status_code >= 300:
            raise FetchError.from_response(response)
        payload = decode_json(response, UploadFilesResponse201)
        return FetchResponse(body=payload, status=response.status_code, headers=response.headers)

    async def delete_file(
        self,
        id: str,
        headers: dict[str, str] | None = None,
    ) -> FetchResponse[None]:
        url = f"{self.base_url}/files/{_escape_path(id)}"
        query = None
        request = self._http.build_request(
            "DELETE",
            url,
            params=query,
            headers=headers,
        )
        response = await self._fetch(request)
        if response.status_code >= 300:
            raise FetchError.from_response(response)
        payload = None
        return FetchResponse(body=payload, status=response.status_code, headers=response.headers)

    async def get_file(
        self,
        id: str,
        params: GetFileParams | None = None,
        headers: dict[str, str] | None = None,
    ) -> FetchResponse[bytes]:
        url = f"{self.base_url}/files/{_escape_path(id)}"

        query: list[tuple[str, str]] = []
        if params is not None and params.q is not None:
            query.extend(_query_parameter("q", params.q, "form", True))
        if params is not None and params.h is not None:
            query.extend(_query_parameter("h", params.h, "form", True))
        if params is not None and params.w is not None:
            query.extend(_query_parameter("w", params.w, "form", True))
        if params is not None and params.b is not None:
            query.extend(_query_parameter("b", params.b, "form", True))
        if params is not None and params.f is not None:
            query.extend(_query_parameter("f", params.f, "form", True))

        _parameter_headers: dict[str, str] = {}
        if params is not None and params.if_match is not None:
            _parameter_headers["if-match"] = _header_value(params.if_match, False)
        if params is not None and params.if_none_match is not None:
            _parameter_headers["if-none-match"] = _header_value(params.if_none_match, False)
        if params is not None and params.if_modified_since is not None:
            _parameter_headers["if-modified-since"] = _header_value(params.if_modified_since, False)
        if params is not None and params.if_unmodified_since is not None:
            _parameter_headers["if-unmodified-since"] = _header_value(
                params.if_unmodified_since, False
            )
        if params is not None and params.range is not None:
            _parameter_headers["Range"] = _header_value(params.range, False)
        request = self._http.build_request(
            "GET",
            url,
            params=query,
            headers={**_parameter_headers, **(headers or {})},
        )
        response = await self._fetch(request)
        if response.status_code >= 300:
            raise FetchError.from_response(response)
        payload = response.content
        return FetchResponse(body=payload, status=response.status_code, headers=response.headers)

    async def get_file_metadata_headers(
        self,
        id: str,
        params: GetFileMetadataHeadersParams | None = None,
        headers: dict[str, str] | None = None,
    ) -> FetchResponse[None]:
        url = f"{self.base_url}/files/{_escape_path(id)}"

        query: list[tuple[str, str]] = []
        if params is not None and params.q is not None:
            query.extend(_query_parameter("q", params.q, "form", True))
        if params is not None and params.h is not None:
            query.extend(_query_parameter("h", params.h, "form", True))
        if params is not None and params.w is not None:
            query.extend(_query_parameter("w", params.w, "form", True))
        if params is not None and params.b is not None:
            query.extend(_query_parameter("b", params.b, "form", True))
        if params is not None and params.f is not None:
            query.extend(_query_parameter("f", params.f, "form", True))

        _parameter_headers: dict[str, str] = {}
        if params is not None and params.if_match is not None:
            _parameter_headers["if-match"] = _header_value(params.if_match, False)
        if params is not None and params.if_none_match is not None:
            _parameter_headers["if-none-match"] = _header_value(params.if_none_match, False)
        if params is not None and params.if_modified_since is not None:
            _parameter_headers["if-modified-since"] = _header_value(params.if_modified_since, False)
        if params is not None and params.if_unmodified_since is not None:
            _parameter_headers["if-unmodified-since"] = _header_value(
                params.if_unmodified_since, False
            )
        request = self._http.build_request(
            "HEAD",
            url,
            params=query,
            headers={**_parameter_headers, **(headers or {})},
        )
        response = await self._fetch(request)
        if response.status_code >= 300:
            raise FetchError.from_response(response)
        payload = None
        return FetchResponse(body=payload, status=response.status_code, headers=response.headers)

    async def replace_file(
        self,
        id: str,
        body: ReplaceFileBody,
        headers: dict[str, str] | None = None,
    ) -> FetchResponse[FileMetadata]:
        url = f"{self.base_url}/files/{_escape_path(id)}"
        query = None
        _data: dict[str, Any] = {}
        _files: list[tuple[str, Any]] = []
        if body.metadata is not None:
            _files.append(("metadata", (None, to_json(body.metadata), "application/json")))
        if body.file is not None:
            _files.append(("file", to_file_part(body.file)))
        request = self._http.build_request(
            "PUT",
            url,
            params=query,
            data=_data or None,
            files=_files or None,
            headers=headers,
        )
        response = await self._fetch(request)
        if response.status_code >= 300:
            raise FetchError.from_response(response)
        payload = decode_json(response, FileMetadata)
        return FetchResponse(body=payload, status=response.status_code, headers=response.headers)

    async def get_file_presigned_url(
        self,
        id: str,
        headers: dict[str, str] | None = None,
    ) -> FetchResponse[PresignedURLResponse]:
        url = f"{self.base_url}/files/{_escape_path(id)}/presignedurl"
        query = None
        request = self._http.build_request(
            "GET",
            url,
            params=query,
            headers=headers,
        )
        response = await self._fetch(request)
        if response.status_code >= 300:
            raise FetchError.from_response(response)
        payload = decode_json(response, PresignedURLResponse)
        return FetchResponse(body=payload, status=response.status_code, headers=response.headers)

    async def delete_broken_metadata(
        self,
        headers: dict[str, str] | None = None,
    ) -> FetchResponse[DeleteBrokenMetadataResponse200]:
        url = f"{self.base_url}/ops/delete-broken-metadata"
        query = None
        request = self._http.build_request(
            "POST",
            url,
            params=query,
            headers=headers,
        )
        response = await self._fetch(request)
        if response.status_code >= 300:
            raise FetchError.from_response(response)
        payload = decode_json(response, DeleteBrokenMetadataResponse200)
        return FetchResponse(body=payload, status=response.status_code, headers=response.headers)

    async def delete_orphaned_files(
        self,
        headers: dict[str, str] | None = None,
    ) -> FetchResponse[DeleteOrphanedFilesResponse200]:
        url = f"{self.base_url}/ops/delete-orphans"
        query = None
        request = self._http.build_request(
            "POST",
            url,
            params=query,
            headers=headers,
        )
        response = await self._fetch(request)
        if response.status_code >= 300:
            raise FetchError.from_response(response)
        payload = decode_json(response, DeleteOrphanedFilesResponse200)
        return FetchResponse(body=payload, status=response.status_code, headers=response.headers)

    async def list_broken_metadata(
        self,
        headers: dict[str, str] | None = None,
    ) -> FetchResponse[ListBrokenMetadataResponse200]:
        url = f"{self.base_url}/ops/list-broken-metadata"
        query = None
        request = self._http.build_request(
            "POST",
            url,
            params=query,
            headers=headers,
        )
        response = await self._fetch(request)
        if response.status_code >= 300:
            raise FetchError.from_response(response)
        payload = decode_json(response, ListBrokenMetadataResponse200)
        return FetchResponse(body=payload, status=response.status_code, headers=response.headers)

    async def list_files_not_uploaded(
        self,
        headers: dict[str, str] | None = None,
    ) -> FetchResponse[ListFilesNotUploadedResponse200]:
        url = f"{self.base_url}/ops/list-not-uploaded"
        query = None
        request = self._http.build_request(
            "POST",
            url,
            params=query,
            headers=headers,
        )
        response = await self._fetch(request)
        if response.status_code >= 300:
            raise FetchError.from_response(response)
        payload = decode_json(response, ListFilesNotUploadedResponse200)
        return FetchResponse(body=payload, status=response.status_code, headers=response.headers)

    async def list_orphaned_files(
        self,
        headers: dict[str, str] | None = None,
    ) -> FetchResponse[ListOrphanedFilesResponse200]:
        url = f"{self.base_url}/ops/list-orphans"
        query = None
        request = self._http.build_request(
            "POST",
            url,
            params=query,
            headers=headers,
        )
        response = await self._fetch(request)
        if response.status_code >= 300:
            raise FetchError.from_response(response)
        payload = decode_json(response, ListOrphanedFilesResponse200)
        return FetchResponse(body=payload, status=response.status_code, headers=response.headers)

    async def get_version(
        self,
        headers: dict[str, str] | None = None,
    ) -> FetchResponse[VersionInformation]:
        url = f"{self.base_url}/version"
        query = None
        request = self._http.build_request(
            "GET",
            url,
            params=query,
            headers=headers,
        )
        response = await self._fetch(request)
        if response.status_code >= 300:
            raise FetchError.from_response(response)
        payload = decode_json(response, VersionInformation)
        return FetchResponse(body=payload, status=response.status_code, headers=response.headers)


def create_api_client(
    base_url: str,
    chain_functions: list[ChainFunction] | None = None,
    http_client: httpx.AsyncClient | None = None,
) -> Client:
    """Create a new API client."""
    return Client(base_url, chain_functions, http_client)


__all__ = [
    "RFC2822Date",
    "ErrorResponseError",
    "ErrorResponse",
    "ErrorResponseWithProcessedFilesError",
    "ErrorResponseWithProcessedFiles",
    "FileMetadata",
    "FileSummary",
    "PresignedURLResponse",
    "UpdateFileMetadata",
    "UploadFileMetadata",
    "VersionInformation",
    "OutputImageFormat",
    "UploadFilesBody",
    "UploadFilesResponse201",
    "ReplaceFileBody",
    "DeleteBrokenMetadataResponse200",
    "DeleteOrphanedFilesResponse200",
    "ListBrokenMetadataResponse200",
    "ListFilesNotUploadedResponse200",
    "ListOrphanedFilesResponse200",
    "GetFileParams",
    "GetFileMetadataHeadersParams",
    "Client",
    "create_api_client",
]
