import './globals.css'

import Navigation from '@components/navigation'

import NhostClientProvider from '@providers/NhostClientProvider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nhost <> Next.JS App Router',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NhostClientProvider>
          <div className="app">
            <Navigation />

            <div className="container p-4 mx-auto mt-8 antialiased">{children}</div>
          </div>
        </NhostClientProvider>
      </body>
    </html>
  )
}
