fragment Project on apps {
  ...ProjectBase
  config(resolve: true) {
    observability {
      grafana {
        adminPassword
      }
    }
    hasura {
      adminSecret
      settings {
        enableConsole
      }
    }
    ai {
      version
    }
  }
}
