// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nhost/nhost/services/constellation/connector/composer (interfaces: computedJoinKeyResolver)
//
// Generated by this command:
//
//	mockgen -package mock -destination mock/computed_join_key_resolver.go . computedJoinKeyResolver
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockcomputedJoinKeyResolver is a mock of computedJoinKeyResolver interface.
type MockcomputedJoinKeyResolver struct {
	ctrl     *gomock.Controller
	recorder *MockcomputedJoinKeyResolverMockRecorder
	isgomock struct{}
}

// MockcomputedJoinKeyResolverMockRecorder is the mock recorder for MockcomputedJoinKeyResolver.
type MockcomputedJoinKeyResolverMockRecorder struct {
	mock *MockcomputedJoinKeyResolver
}

// NewMockcomputedJoinKeyResolver creates a new mock instance.
func NewMockcomputedJoinKeyResolver(ctrl *gomock.Controller) *MockcomputedJoinKeyResolver {
	mock := &MockcomputedJoinKeyResolver{ctrl: ctrl}
	mock.recorder = &MockcomputedJoinKeyResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcomputedJoinKeyResolver) EXPECT() *MockcomputedJoinKeyResolverMockRecorder {
	return m.recorder
}

// HasComputedJoinKey mocks base method.
func (m *MockcomputedJoinKeyResolver) HasComputedJoinKey(tableSchema, tableName, key string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasComputedJoinKey", tableSchema, tableName, key)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasComputedJoinKey indicates an expected call of HasComputedJoinKey.
func (mr *MockcomputedJoinKeyResolverMockRecorder) HasComputedJoinKey(tableSchema, tableName, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasComputedJoinKey", reflect.TypeOf((*MockcomputedJoinKeyResolver)(nil).HasComputedJoinKey), tableSchema, tableName, key)
}
