/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [
    'index',
    {
      label: 'Framework Starters',
      type: 'category',
      link: {
        type: 'doc',
        id: 'framework-starters/index',
      },
      collapsed: false,
      items: [
        'framework-starters/quick-start-react',
        'framework-starters/quick-start-nextjs',
        'framework-starters/quick-start-react-native',
      ],
    },
    'database',
    'graphql',
    {
      label: 'Authentication',
      type: 'category',
      link: {
        type: 'doc',
        id: 'authentication/index',
      },
      items: [
        {
          label: 'OAuth Providers',
          type: 'category',
          items: [
            'authentication/oauth-providers/google',
            'authentication/oauth-providers/facebook',
            'authentication/oauth-providers/github',
            'authentication/oauth-providers/linkedin',
            'authentication/oauth-providers/spotify',
          ],
        },
        'authentication/email-templates',
      ],
    },
    'storage/index',
    'functions/index',
    'cli/index',
  ],
  referenceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'reference',
    },
  ],
};

module.exports = sidebars;
