// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nhost/nhost/services/ai/agents/provider (interfaces: Provider)
//
// Generated by this command:
//
//	mockgen -package mock -destination mock/provider.go . Provider
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	provider "github.com/nhost/nhost/services/ai/agents/provider"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// StreamResponse mocks base method.
func (m *MockProvider) StreamResponse(ctx context.Context, systemPrompt string, messages []provider.Message, tools []provider.ToolDefinition) <-chan provider.Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamResponse", ctx, systemPrompt, messages, tools)
	ret0, _ := ret[0].(<-chan provider.Event)
	return ret0
}

// StreamResponse indicates an expected call of StreamResponse.
func (mr *MockProviderMockRecorder) StreamResponse(ctx, systemPrompt, messages, tools any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamResponse", reflect.TypeOf((*MockProvider)(nil).StreamResponse), ctx, systemPrompt, messages, tools)
}
