#!/bin/sh

set -e

# read URLs from env variables
NEXT_PUBLIC_NHOST_AUTH_URL=${NEXT_PUBLIC_NHOST_AUTH_URL}
NEXT_PUBLIC_NHOST_FUNCTIONS_URL=${NEXT_PUBLIC_NHOST_FUNCTIONS_URL}
NEXT_PUBLIC_NHOST_GRAPHQL_URL=${NEXT_PUBLIC_NHOST_GRAPHQL_URL}
NEXT_PUBLIC_NHOST_STORAGE_URL=${NEXT_PUBLIC_NHOST_STORAGE_URL}
NEXT_PUBLIC_NHOST_HASURA_CONSOLE_URL=${NEXT_PUBLIC_NHOST_HASURA_CONSOLE_URL}
NEXT_PUBLIC_NHOST_HASURA_MIGRATIONS_API_URL=${NEXT_PUBLIC_NHOST_HASURA_MIGRATIONS_API_URL}
NEXT_PUBLIC_NHOST_HASURA_SCHEMA_API_URL=${NEXT_PUBLIC_NHOST_HASURA_SCHEMA_API_URL}

# replace placeholders
find dashboard -type f -exec sed -i "s/__NEXT_PUBLIC_NHOST_AUTH_URL__/${NEXT_PUBLIC_NHOST_AUTH_URL}/g" {} +
find dashboard -type f -exec sed -i "s/__NEXT_PUBLIC_NHOST_FUNCTIONS_URL__/${NEXT_PUBLIC_NHOST_FUNCTIONS_URL}/g" {} +
find dashboard -type f -exec sed -i "s/__NEXT_PUBLIC_NHOST_GRAPHQL_URL__/${NEXT_PUBLIC_NHOST_GRAPHQL_URL}/g" {} +
find dashboard -type f -exec sed -i "s/__NEXT_PUBLIC_NHOST_STORAGE_URL__/${NEXT_PUBLIC_NHOST_STORAGE_URL}/g" {} +
find dashboard -type f -exec sed -i "s/__NEXT_PUBLIC_NHOST_HASURA_CONSOLE_URL__/${NEXT_PUBLIC_NHOST_HASURA_CONSOLE_URL}/g" {} +
find dashboard -type f -exec sed -i "s/__NEXT_PUBLIC_NHOST_HASURA_MIGRATIONS_API_URL__/${NEXT_PUBLIC_NHOST_HASURA_MIGRATIONS_API_URL}/g" {} +
find dashboard -type f -exec sed -i "s/__NEXT_PUBLIC_NHOST_HASURA_SCHEMA_API_URL__/${NEXT_PUBLIC_NHOST_HASURA_SCHEMA_API_URL}/g" {} +

exec "$@"
