ROOT_DIR?=$(abspath ../)
include $(ROOT_DIR)/build/makefiles/general.makefile


.PHONY: _check-pre
_check-pre:
	@sed -i 's/$$NHOST_PAT/$(NHOST_PAT)/' get_access_token.sh


.PHONY: _dev-env-up
_dev-env-up:
	@echo "Nothing to do"


.PHONY: _dev-env-down
_dev-env-down:
	@echo "Nothing to do"


.PHONY: _dev-env-build
_dev-env-build:
	@echo "Nothing to do"
