fragment GetAppLoginData on apps {
  id
  slug
  subdomain
  name
  createdAt

  authEmailSigninEmailVerifiedRequired
  authPasswordHibpEnabled

  authEmailPasswordlessEnabled
  authSmsPasswordlessEnabled
  authWebAuthnEnabled

  authClientUrl
  authAccessControlAllowedRedirectUrls

  authAccessControlAllowedEmails
  authAccessControlAllowedEmailDomains
  authAccessControlBlockedEmails
  authAccessControlBlockedEmailDomains

  authGithubEnabled
  authGithubClientId
  authGithubClientSecret
  authGoogleEnabled
  authGoogleClientId
  authGoogleClientSecret

  authFacebookEnabled
  authFacebookClientId
  authFacebookClientSecret

  authLinkedinEnabled
  authLinkedinClientId
  authLinkedinClientSecret

  # Twitter
  authTwitterEnabled
  authTwitterConsumerKey
  authTwitterConsumerSecret

  # Apple
  authAppleEnabled
  authAppleTeamId
  authAppleKeyId
  authAppleClientId
  authApplePrivateKey
  authAppleScope

  # Windows Live
  authWindowsLiveEnabled
  authWindowsLiveClientId
  authWindowsLiveClientSecret

  # Spotify
  authSpotifyEnabled
  authSpotifyClientId
  authSpotifyClientSecret

  # WorkOs
  authWorkOsEnabled
  authWorkOsClientId
  authWorkOsClientSecret
  authWorkOsDefaultDomain
  authWorkOsDefaultOrganization
  authWorkOsDefaultConnection

  # Discord
  authDiscordEnabled
  authDiscordClientId
  authDiscordClientSecret

  # Twitch
  authTwitchEnabled
  authTwitchClientId
  authTwitchClientSecret
}

query getAppLoginData($id: uuid!) {
  app(id: $id) {
    ...GetAppLoginData
  }
}
