query getProjectServicesHealth($appId: String!){
  getProjectStatus(appID: $appId) {
    Services {
      Name
      State
      Replicas {
        Ready
        Date
        Errors {
          Name
          LastError {
            Reason
            ExitCode
            Message
          }
        }
      }
    }
  }
}
