query GetProjectMetrics(
  $appId: String!
  $subdomain: String!
  $from: Timestamp
  $to: Timestamp
) {
  logsVolume: getLogsVolume(appID: $appId, from: $from, to: $to) {
    value
  }
  cpuSecondsUsage: getCPUSecondsUsage(appID: $appId, from: $from, to: $to) {
    value
  }
  functionInvocations: getFunctionsInvocations(
    appID: $appId
    from: $from
    to: $to
  ) {
    value
  }
  functionsDuration: getFunctionsDuration(appID: $appId, from: $from, to: $to) {
    value
  }
  postgresVolumeCapacity: getPostgresVolumeCapacity(appID: $appId) {
    value
  }
  postgresVolumeUsage: getPostgresVolumeUsage(appID: $appId) {
    value
  }
  totalRequests: getTotalRequests(appID: $appId, from: $from, to: $to) {
    value
  }
  egressVolume: getEgressVolume(
    appID: $appId
    subdomain: $subdomain
    from: $from
    to: $to
  ) {
    value
  }
}
