version: "2"
linters:
  default: all
  disable:
    - depguard
    - gomoddirectives
    - nlreturn
    - usestdlibvars
    - varnamelen
    - wsl
    - noinlineerr
    - funcorder
    - canonicalheader
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gochecknoglobals
          - gochecknoinits
        path: cmd/
      - linters:
          - lll
        source: '^//go:generate '
      - linters:
          - gochecknoglobals
        path: controller/version.go
      - linters:
          - funlen
          - ireturn
          - exhaustruct
        path: _test\.go
      - linters:
          - nosnakecase
        path: image/image.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
