ROOT_DIR?=$(abspath ../..)
include $(ROOT_DIR)/build/makefiles/general.makefile

DOCKER_DEV_ENV_PATH=build/dev/docker


.PHONY: _dev-env-up
_dev-env-up:
	echo TBD


.PHONY: _dev-env-down
_dev-env-down:
	echo TBD


.PHONY: _dev-env-build
_dev-env-build: build-docker-image
	echo TBD
