{
 "title": "Functions Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "method",
    "query": {
     "query": "label_values(functions_requests_total, method)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values(functions_requests_total, route)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Number of Invocations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(functions_requests_total{method=~\"$method\",route=~\"$route\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(functions_bytes_sent{method=~\"$method\",route=~\"$route\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(functions_duration_seconds_sum{method=~\"$method\",route=~\"$route\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Invocations",
   "type": "timeseries",
   "description": "Number of invocations by method/function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(method, route) (increase(functions_requests_total{method=~\"$method\",route=~\"$route\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "timeseries",
   "description": "Number of invocations by status response",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(status) (increase(functions_requests_total{method=~\"$method\",route=~\"$route\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average Response Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(method, route) (increase(functions_bytes_sent{method=~\"$method\", route=~\"$route\"}[$__rate_interval])) / sum by(method, route) (increase(functions_requests_total{method=~\"$method\", route=~\"$route\"}[$__rate_interval]))",
     "legendFormat": "{{ method }} - {{ route }}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "ceil(sum by(route, method) (increase(functions_requests_total{method=~\"$method\",route=~\"$route\"}[$__range])))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  { "title": "Response Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Maximum Response Time",
   "type": "timeseries",
   "description": "Time the slowest response took",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, rate(functions_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "{{ method }} - {{ route }}"
    }
   ]
  },
  {
   "title": "Response times 95th percentile",
   "type": "timeseries",
   "description": "The 95th percentile of response times refers to the value below which 95% of response times fall. In other words, it is the point at which only 5% of response times are higher",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(functions_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "{{ method }} - {{ route }}"
    }
   ]
  },
  {
   "title": "Response times 75th percentile",
   "type": "timeseries",
   "description": "The 75th percentile of response times refers to the value below which 75% of response times fall. In other words, it is the point at which 25% of response times are higher",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, rate(functions_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "{{ method }} - {{ route }}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(method, route) (increase(functions_duration_seconds_sum{method=~\"$method\", route=~\"$route\"}[$__rate_interval])) / sum by(method, route) (increase(functions_duration_seconds_count{method=~\"$method\", route=~\"$route\"}[$__rate_interval]))",
     "legendFormat": "{{ method }} - {{ route }}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "description": "Number of invocations that failed divided by the total number of invocations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(method, route) (increase(functions_requests_total{method=~\"$method\",route=~\"$route\",status=~\"^[4-5].*\"}[$__rate_interval])) / sum by(method, route) (increase(functions_requests_total[$__rate_interval]))",
     "legendFormat": "{{method}} {{ route }}"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "ceil(sum by(route, method,status) (increase(functions_requests_total{method=~\"$method\",route=~\"$route\",status=~\"^[4-5].*\"}[$__range])))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  }
 ]
}