/**
 * SQL template for fetching column metadata from a table.
 *
 * Uses positional pg-format parameters:
 *   %1$ = schema name
 *   %2$ = table name
 *
 * Returns: column info joined with PG_CATALOG data for FULL_DATA_TYPE,
 * IS_PRIMARY, IS_UNIQUE, and COLUMN_COMMENT.
 */
export const COLUMN_DEFINITION_QUERY = `
  SELECT ROW_TO_JSON(TABLE_DATA) FROM (
      SELECT *,
          PG_CATALOG.FORMAT_TYPE(
              (SELECT ATTTYPID FROM PG_ATTRIBUTE
               WHERE ATTRELID = (SELECT OID FROM PG_CLASS WHERE RELNAME = %2$L AND RELNAMESPACE = (SELECT OID FROM PG_NAMESPACE WHERE NSPNAME = %1$L))
               AND ATTNAME = COLS.COLUMN_NAME),
              (SELECT ATTTYPMOD FROM PG_ATTRIBUTE
               WHERE ATTRELID = (SELECT OID FROM PG_CLASS WHERE RELNAME = %2$L AND RELNAMESPACE = (SELECT OID FROM PG_NAMESPACE WHERE NSPNAME = %1$L))
               AND ATTNAME = COLS.COLUMN_NAME)
          ) AS FULL_DATA_TYPE,
          EXISTS (
              SELECT NSP.NSPNAME, CLS.RELNAME, ATTR.ATTNAME
              FROM PG_INDEX IND
              JOIN PG_CLASS CLS ON CLS.OID = IND.INDRELID
              JOIN PG_ATTRIBUTE ATTR ON ATTR.ATTRELID = CLS.OID AND ATTR.ATTNUM = ANY(IND.INDKEY)
              JOIN PG_NAMESPACE NSP ON NSP.OID = CLS.RELNAMESPACE
              WHERE NSPNAME = %1$L AND RELNAME = %2$L AND ATTR.ATTNAME = COLS.COLUMN_NAME AND INDISPRIMARY
          ) AS IS_PRIMARY,
          EXISTS (
              SELECT NSP.NSPNAME, CLS.RELNAME, ATTR.ATTNAME
              FROM PG_INDEX IND
              JOIN PG_CLASS CLS ON CLS.OID = IND.INDRELID
              JOIN PG_ATTRIBUTE ATTR ON ATTR.ATTRELID = CLS.OID AND ATTR.ATTNUM = ANY(IND.INDKEY)
              JOIN PG_NAMESPACE NSP ON NSP.OID = CLS.RELNAMESPACE
              WHERE NSPNAME = %1$L AND RELNAME = %2$L AND ATTR.ATTNAME = COLS.COLUMN_NAME AND INDISUNIQUE
          ) AS IS_UNIQUE,
          (
              SELECT PG_CATALOG.COL_DESCRIPTION(CLS.OID, COLS.ORDINAL_POSITION::INT)
              FROM PG_CATALOG.PG_CLASS CLS
              WHERE CLS.OID = (SELECT '%1$I.%2$I'::REGCLASS::OID) AND CLS.RELNAME = COLS.TABLE_NAME
          ) AS COLUMN_COMMENT
      FROM INFORMATION_SCHEMA.COLUMNS COLS
      WHERE TABLE_SCHEMA = %1$L AND TABLE_NAME = %2$L
  ) TABLE_DATA;
`;

/**
 * SQL template for fetching column metadata from a materialized view.
 *
 * Uses PG_ATTRIBUTE as the base since materialized views are absent
 * from INFORMATION_SCHEMA.COLUMNS.
 *
 * Uses positional pg-format parameters:
 *   %1$ = schema name
 *   %2$ = table name
 */
export const MATERIALIZED_VIEW_COLUMN_DEFINITION_QUERY = `
  SELECT ROW_TO_JSON(TABLE_DATA) FROM (
    SELECT
      ATTR.ATTNAME AS COLUMN_NAME,
      ATTR.ATTNUM AS ORDINAL_POSITION,
      CASE WHEN AD.ADBIN IS NOT NULL THEN PG_GET_EXPR(AD.ADBIN, AD.ADRELID, true) ELSE NULL END AS COLUMN_DEFAULT,
      CASE WHEN ATTR.ATTNOTNULL THEN 'NO' ELSE 'YES' END AS IS_NULLABLE,
      TYP.TYPNAME AS DATA_TYPE,
      TYP.TYPNAME AS UDT_NAME,
      NULL AS CHARACTER_MAXIMUM_LENGTH,
      NULL AS NUMERIC_PRECISION,
      NULL AS NUMERIC_SCALE,
      NULL AS DATETIME_PRECISION,
      'NO' AS IS_IDENTITY,
      PG_CATALOG.FORMAT_TYPE(ATTR.ATTTYPID, ATTR.ATTTYPMOD) AS FULL_DATA_TYPE,
      EXISTS (
        SELECT 1
        FROM PG_INDEX IND
        WHERE IND.INDRELID = CLS.OID
        AND ATTR.ATTNUM = ANY(IND.INDKEY)
        AND IND.INDISPRIMARY
      ) AS IS_PRIMARY,
      EXISTS (
        SELECT 1
        FROM PG_INDEX IND
        WHERE IND.INDRELID = CLS.OID
        AND ATTR.ATTNUM = ANY(IND.INDKEY)
        AND IND.INDISUNIQUE
        AND NOT IND.INDISPRIMARY
      ) AS IS_UNIQUE,
      PG_CATALOG.COL_DESCRIPTION(CLS.OID, ATTR.ATTNUM) AS COLUMN_COMMENT
    FROM PG_ATTRIBUTE ATTR
    JOIN PG_CLASS CLS ON CLS.OID = ATTR.ATTRELID
    JOIN PG_NAMESPACE NSP ON NSP.OID = CLS.RELNAMESPACE
    JOIN PG_TYPE TYP ON TYP.OID = ATTR.ATTTYPID
    LEFT JOIN PG_ATTRDEF AD ON AD.ADRELID = CLS.OID AND AD.ADNUM = ATTR.ATTNUM
    WHERE NSP.NSPNAME = %1$L
    AND CLS.RELNAME = %2$L
    AND ATTR.ATTNUM > 0
    AND NOT ATTR.ATTISDROPPED
  ) TABLE_DATA
  ORDER BY ORDINAL_POSITION;
`;

/**
 * SQL template for fetching constraint definitions from a table.
 *
 * Uses positional pg-format parameters:
 *   %1$ = schema name (identifier)
 *   %2$ = table name (identifier)
 *
 * Returns: object name, constraint/synthetic index type, definition, column
 * name, and key-column ordinality for each constraint or eligible standalone
 * unique index.
 */
export const CONSTRAINT_DEFINITION_QUERY = `SELECT ROW_TO_JSON(TABLE_DATA) FROM (\
  SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, CONSTRAINT_DEFINITION, COLUMN_NAME, COLUMN_ORDINALITY
  FROM (
    SELECT CON.CONNAME AS CONSTRAINT_NAME, CON.CONTYPE AS CONSTRAINT_TYPE, PG_GET_CONSTRAINTDEF(CON.OID) AS CONSTRAINT_DEFINITION, ATTR.ATTNAME AS COLUMN_NAME, AK.ORDINALITY AS COLUMN_ORDINALITY
    FROM PG_CONSTRAINT CON
    CROSS JOIN LATERAL UNNEST(CON.CONKEY) WITH ORDINALITY AS AK(K, ORDINALITY)
    INNER JOIN PG_ATTRIBUTE ATTR
      ON ATTR.ATTRELID = CON.CONRELID
      AND ATTR.ATTNUM = AK.K
    WHERE CON.CONRELID = '%1$I.%2$I'::REGCLASS

    UNION ALL

    SELECT INDEX_CLASS.RELNAME AS CONSTRAINT_NAME, 'i'::"char" AS CONSTRAINT_TYPE, NULL::TEXT AS CONSTRAINT_DEFINITION, ATTR.ATTNAME AS COLUMN_NAME, AK.ORDINALITY AS COLUMN_ORDINALITY
    FROM PG_INDEX IDX
    INNER JOIN PG_CLASS INDEX_CLASS
      ON INDEX_CLASS.OID = IDX.INDEXRELID
    CROSS JOIN LATERAL UNNEST(IDX.INDKEY) WITH ORDINALITY AS AK(K, ORDINALITY)
    INNER JOIN PG_ATTRIBUTE ATTR
      ON ATTR.ATTRELID = IDX.INDRELID
      AND ATTR.ATTNUM = AK.K
      AND ATTR.ATTNUM > 0
    WHERE IDX.INDRELID = '%1$I.%2$I'::REGCLASS
      AND AK.ORDINALITY <= IDX.INDNKEYATTS
      AND IDX.INDISUNIQUE
      AND IDX.INDISVALID
      AND IDX.INDISREADY
      AND IDX.INDISLIVE
      AND NOT IDX.INDISPRIMARY
      AND IDX.INDPRED IS NULL
      AND IDX.INDEXPRS IS NULL
      AND NOT EXISTS (
        SELECT 1
        FROM PG_CONSTRAINT CON
        WHERE CON.CONINDID = IDX.INDEXRELID
      )
  ) CONSTRAINT_AND_INDEX_DATA
  ORDER BY CONSTRAINT_TYPE, CONSTRAINT_NAME, COLUMN_ORDINALITY
) TABLE_DATA`;
