fragment ServiceResources on ConfigConfig {
  auth {
    resources {
      compute {
        cpu
        memory
      }
      replicas
      autoscaler {
        maxReplicas
      }
      networking {
        ingresses {
          fqdn
        }
      }
    }
  }
  hasura {
    resources {
      compute {
        cpu
        memory
      }
      replicas
      autoscaler {
        maxReplicas
      }
      networking {
        ingresses {
          fqdn
        }
      }
    }
  }
  postgres {
    resources {
      storage {
        capacity
      }
      enablePublicAccess
      compute {
        cpu
        memory
      }
    }
  }
  storage {
    resources {
      compute {
        cpu
        memory
      }
      replicas
      autoscaler {
        maxReplicas
      }
    }
  }
}

query GetResources($appId: uuid!) {
  config(appID: $appId, resolve: false) {
    ...ServiceResources
  }
}
