fragment ServiceResources on ConfigConfig {
  auth {
    resources {
      compute {
        cpu
        memory
      }
      replicas
      autoscaler {
        maxReplicas
      }
    }
  }
  hasura {
    resources {
      compute {
        cpu
        memory
      }
      replicas
      autoscaler {
        maxReplicas
      }
    }
  }
  postgres {
    resources {
      compute {
        cpu
        memory
      }
      replicas
      autoscaler {
        maxReplicas
      }
    }
  }
  storage {
    resources {
      compute {
        cpu
        memory
      }
      replicas
      autoscaler {
        maxReplicas
      }
    }
  }
}

query GetResources($appId: uuid!) {
  config(appID: $appId, resolve: false) {
    ...ServiceResources
  }
}
