query getAnnouncements {
  announcements(
    order_by: { createdAt: desc }
    where: {
      _or: [{ expiresAt: { _is_null: true } }, { expiresAt: { _gt: now } }]
    }
  ) {
    id
    href
    content
    createdAt
    read {
      id
    }
  }
}
