query getPlans {
  plans(order_by: { sort: asc }) {
    id
    name
    isFree
    price
    isDefault
  }
  regions {
    id
    isGdprCompliant
    city
    country {
      name
      continent {
        name
      }
    }
  }
  workspaces {
    id
    name
    slug
    paymentMethods {
      id
      cardBrand
      cardLast4
    }
  }
}
