// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version (devel) DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /healthz)
	GetHealthz(c *gin.Context)
	// Health check
	// (HEAD /healthz)
	HeadHealthz(c *gin.Context)
	// Create a Personal Access Token (PAT)
	// (POST /pat)
	PostPat(c *gin.Context)
	// Sign in with email and password
	// (POST /signin/email-password)
	PostSigninEmailPassword(c *gin.Context)
	// Sign in with magic link sent to user's email. If user doesn't exist, it will be created. The options object is optional and can be used to set the user's when signing up a new user. It is ignored if the user already exists.
	// (POST /signin/passwordless/email)
	PostSigninPasswordlessEmail(c *gin.Context)
	// Sign in with Personal Access Token (PAT)
	// (POST /signin/pat)
	PostSigninPat(c *gin.Context)
	// Signup with email and password
	// (POST /signup/email-password)
	PostSignupEmailPassword(c *gin.Context)
	// Change user email
	// (POST /user/email/change)
	PostUserEmailChange(c *gin.Context)
	// Request a password reset. An email with a verification link will be sent to the user's address
	// (POST /user/password/reset)
	PostUserPasswordReset(c *gin.Context)
	// Get version
	// (GET /version)
	GetVersion(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealthz(c)
}

// HeadHealthz operation middleware
func (siw *ServerInterfaceWrapper) HeadHealthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HeadHealthz(c)
}

// PostPat operation middleware
func (siw *ServerInterfaceWrapper) PostPat(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPat(c)
}

// PostSigninEmailPassword operation middleware
func (siw *ServerInterfaceWrapper) PostSigninEmailPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSigninEmailPassword(c)
}

// PostSigninPasswordlessEmail operation middleware
func (siw *ServerInterfaceWrapper) PostSigninPasswordlessEmail(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSigninPasswordlessEmail(c)
}

// PostSigninPat operation middleware
func (siw *ServerInterfaceWrapper) PostSigninPat(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSigninPat(c)
}

// PostSignupEmailPassword operation middleware
func (siw *ServerInterfaceWrapper) PostSignupEmailPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSignupEmailPassword(c)
}

// PostUserEmailChange operation middleware
func (siw *ServerInterfaceWrapper) PostUserEmailChange(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUserEmailChange(c)
}

// PostUserPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) PostUserPasswordReset(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUserPasswordReset(c)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVersion(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealthz)
	router.HEAD(options.BaseURL+"/healthz", wrapper.HeadHealthz)
	router.POST(options.BaseURL+"/pat", wrapper.PostPat)
	router.POST(options.BaseURL+"/signin/email-password", wrapper.PostSigninEmailPassword)
	router.POST(options.BaseURL+"/signin/passwordless/email", wrapper.PostSigninPasswordlessEmail)
	router.POST(options.BaseURL+"/signin/pat", wrapper.PostSigninPat)
	router.POST(options.BaseURL+"/signup/email-password", wrapper.PostSignupEmailPassword)
	router.POST(options.BaseURL+"/user/email/change", wrapper.PostUserEmailChange)
	router.POST(options.BaseURL+"/user/password/reset", wrapper.PostUserPasswordReset)
	router.GET(options.BaseURL+"/version", wrapper.GetVersion)
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse OKResponse

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type HeadHealthzRequestObject struct {
}

type HeadHealthzResponseObject interface {
	VisitHeadHealthzResponse(w http.ResponseWriter) error
}

type HeadHealthz200Response struct {
}

func (response HeadHealthz200Response) VisitHeadHealthzResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PostPatRequestObject struct {
	Body *PostPatJSONRequestBody
}

type PostPatResponseObject interface {
	VisitPostPatResponse(w http.ResponseWriter) error
}

type PostPat200JSONResponse CreatePATResponse

func (response PostPat200JSONResponse) VisitPostPatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSigninEmailPasswordRequestObject struct {
	Body *PostSigninEmailPasswordJSONRequestBody
}

type PostSigninEmailPasswordResponseObject interface {
	VisitPostSigninEmailPasswordResponse(w http.ResponseWriter) error
}

type PostSigninEmailPassword200JSONResponse SignInEmailPasswordResponse

func (response PostSigninEmailPassword200JSONResponse) VisitPostSigninEmailPasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSigninPasswordlessEmailRequestObject struct {
	Body *PostSigninPasswordlessEmailJSONRequestBody
}

type PostSigninPasswordlessEmailResponseObject interface {
	VisitPostSigninPasswordlessEmailResponse(w http.ResponseWriter) error
}

type PostSigninPasswordlessEmail200JSONResponse OKResponse

func (response PostSigninPasswordlessEmail200JSONResponse) VisitPostSigninPasswordlessEmailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSigninPatRequestObject struct {
	Body *PostSigninPatJSONRequestBody
}

type PostSigninPatResponseObject interface {
	VisitPostSigninPatResponse(w http.ResponseWriter) error
}

type PostSigninPat200JSONResponse SessionPayload

func (response PostSigninPat200JSONResponse) VisitPostSigninPatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSignupEmailPasswordRequestObject struct {
	Body *PostSignupEmailPasswordJSONRequestBody
}

type PostSignupEmailPasswordResponseObject interface {
	VisitPostSignupEmailPasswordResponse(w http.ResponseWriter) error
}

type PostSignupEmailPassword200JSONResponse SessionPayload

func (response PostSignupEmailPassword200JSONResponse) VisitPostSignupEmailPasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSignupEmailPassword403JSONResponse ErrorResponse

func (response PostSignupEmailPassword403JSONResponse) VisitPostSignupEmailPasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostSignupEmailPassword409JSONResponse ErrorResponse

func (response PostSignupEmailPassword409JSONResponse) VisitPostSignupEmailPasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostUserEmailChangeRequestObject struct {
	Body *PostUserEmailChangeJSONRequestBody
}

type PostUserEmailChangeResponseObject interface {
	VisitPostUserEmailChangeResponse(w http.ResponseWriter) error
}

type PostUserEmailChange200JSONResponse OKResponse

func (response PostUserEmailChange200JSONResponse) VisitPostUserEmailChangeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUserPasswordResetRequestObject struct {
	Body *PostUserPasswordResetJSONRequestBody
}

type PostUserPasswordResetResponseObject interface {
	VisitPostUserPasswordResetResponse(w http.ResponseWriter) error
}

type PostUserPasswordReset200JSONResponse OKResponse

func (response PostUserPasswordReset200JSONResponse) VisitPostUserPasswordResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetVersionRequestObject struct {
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200JSONResponse struct {
	Version string `json:"version"`
}

func (response GetVersion200JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Health check
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// Health check
	// (HEAD /healthz)
	HeadHealthz(ctx context.Context, request HeadHealthzRequestObject) (HeadHealthzResponseObject, error)
	// Create a Personal Access Token (PAT)
	// (POST /pat)
	PostPat(ctx context.Context, request PostPatRequestObject) (PostPatResponseObject, error)
	// Sign in with email and password
	// (POST /signin/email-password)
	PostSigninEmailPassword(ctx context.Context, request PostSigninEmailPasswordRequestObject) (PostSigninEmailPasswordResponseObject, error)
	// Sign in with magic link sent to user's email. If user doesn't exist, it will be created. The options object is optional and can be used to set the user's when signing up a new user. It is ignored if the user already exists.
	// (POST /signin/passwordless/email)
	PostSigninPasswordlessEmail(ctx context.Context, request PostSigninPasswordlessEmailRequestObject) (PostSigninPasswordlessEmailResponseObject, error)
	// Sign in with Personal Access Token (PAT)
	// (POST /signin/pat)
	PostSigninPat(ctx context.Context, request PostSigninPatRequestObject) (PostSigninPatResponseObject, error)
	// Signup with email and password
	// (POST /signup/email-password)
	PostSignupEmailPassword(ctx context.Context, request PostSignupEmailPasswordRequestObject) (PostSignupEmailPasswordResponseObject, error)
	// Change user email
	// (POST /user/email/change)
	PostUserEmailChange(ctx context.Context, request PostUserEmailChangeRequestObject) (PostUserEmailChangeResponseObject, error)
	// Request a password reset. An email with a verification link will be sent to the user's address
	// (POST /user/password/reset)
	PostUserPasswordReset(ctx context.Context, request PostUserPasswordResetRequestObject) (PostUserPasswordResetResponseObject, error)
	// Get version
	// (GET /version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(ctx *gin.Context) {
	var request GetHealthzRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// HeadHealthz operation middleware
func (sh *strictHandler) HeadHealthz(ctx *gin.Context) {
	var request HeadHealthzRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.HeadHealthz(ctx, request.(HeadHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HeadHealthz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(HeadHealthzResponseObject); ok {
		if err := validResponse.VisitHeadHealthzResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostPat operation middleware
func (sh *strictHandler) PostPat(ctx *gin.Context) {
	var request PostPatRequestObject

	var body PostPatJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostPat(ctx, request.(PostPatRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostPat")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostPatResponseObject); ok {
		if err := validResponse.VisitPostPatResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSigninEmailPassword operation middleware
func (sh *strictHandler) PostSigninEmailPassword(ctx *gin.Context) {
	var request PostSigninEmailPasswordRequestObject

	var body PostSigninEmailPasswordJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSigninEmailPassword(ctx, request.(PostSigninEmailPasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSigninEmailPassword")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostSigninEmailPasswordResponseObject); ok {
		if err := validResponse.VisitPostSigninEmailPasswordResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSigninPasswordlessEmail operation middleware
func (sh *strictHandler) PostSigninPasswordlessEmail(ctx *gin.Context) {
	var request PostSigninPasswordlessEmailRequestObject

	var body PostSigninPasswordlessEmailJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSigninPasswordlessEmail(ctx, request.(PostSigninPasswordlessEmailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSigninPasswordlessEmail")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostSigninPasswordlessEmailResponseObject); ok {
		if err := validResponse.VisitPostSigninPasswordlessEmailResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSigninPat operation middleware
func (sh *strictHandler) PostSigninPat(ctx *gin.Context) {
	var request PostSigninPatRequestObject

	var body PostSigninPatJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSigninPat(ctx, request.(PostSigninPatRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSigninPat")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostSigninPatResponseObject); ok {
		if err := validResponse.VisitPostSigninPatResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSignupEmailPassword operation middleware
func (sh *strictHandler) PostSignupEmailPassword(ctx *gin.Context) {
	var request PostSignupEmailPasswordRequestObject

	var body PostSignupEmailPasswordJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSignupEmailPassword(ctx, request.(PostSignupEmailPasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSignupEmailPassword")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostSignupEmailPasswordResponseObject); ok {
		if err := validResponse.VisitPostSignupEmailPasswordResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostUserEmailChange operation middleware
func (sh *strictHandler) PostUserEmailChange(ctx *gin.Context) {
	var request PostUserEmailChangeRequestObject

	var body PostUserEmailChangeJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUserEmailChange(ctx, request.(PostUserEmailChangeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUserEmailChange")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostUserEmailChangeResponseObject); ok {
		if err := validResponse.VisitPostUserEmailChangeResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostUserPasswordReset operation middleware
func (sh *strictHandler) PostUserPasswordReset(ctx *gin.Context) {
	var request PostUserPasswordResetRequestObject

	var body PostUserPasswordResetJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUserPasswordReset(ctx, request.(PostUserPasswordResetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUserPasswordReset")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostUserPasswordResetResponseObject); ok {
		if err := validResponse.VisitPostUserPasswordResetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(ctx *gin.Context) {
	var request GetVersionRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx, request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		if err := validResponse.VisitGetVersionResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xaW3fbuBH+KzjY9qQ9h5QU290meqo2dTfeS6ITK9uHxA8QMSKRkAAXAK2orv57zwAg",
	"RUqUfKntePNm4zKcmW/u0BVNVFEqCdIaOr6iJsmgYO7PVxqYhelk9g5+r8BYXGOcCyuUZPlUqxK0FWDo",
	"eMFyAxEtW0tXFL6UQoOZuHscTKJFiVfpmJ7iFsN/CGcWiFoQmwGZTmY0ogulC2bpmOJWbEUBNKJ2VQId",
	"U2O1kCldR7QAyzizbD9TVlcQUfjCijIHPCZZgTSKVVwySyNaGeDxfOWXWFnGSS6QdPiWmn+CxNL1OqIa",
	"fq+EBk7HH1piXewcjdo6M6WSBm6pNMF3tXX2z66CGpHoUXL8t/n3i+M4OZm/jE9ewHH88u8vWMxP+Gjx",
	"nJ8cwdEJjWjJrAWNpD5+nH8YxS9ZvLi4erH++HEeN/+erPf+3b71/Aiv9SFSgjYo4yRJwJiZ+gxyV5Yn",
	"LMEWzoLTfpn6YD/VWuk7Qg54t8dHcJkkigOxGbNEcJBWLAQYZwqsLHOReB/yFCIKsiqQdQ4LVuU21iqH",
	"uKiMjecQCxmzPFdL4G7d0IhyYdg8Bx6D5KUS0rbXKgOOZsFEHrNcA+MrJFIZ8E46F5yDjJlUclWoCgkK",
	"iSixPDagL0HHNWNCXrJc8NgTK5kxS6V5a0OHCBPRXCUsh1gqW7Pr4Pc3YqtUbDKlbXtRyDgT8zLGcDBn",
	"jj0NXGhIZmqLkNNId8mIVFZlXMuNcUFegkZNN0qo2cS4cdEbjIxhKeyC+LoqmCQLLUDyfOWBIvXpHkLG",
	"MluZHjqz2ZT4zUAEDWNDARWfgt4x4kBvw2EUzK3PiH/91+RVxvIcZApTtsoV47c0ZSuSz+Di/WHfCuf6",
	"mHj7843dqDb3tz/3gvLWKc+886ZgZ+qWwujOxU3IyqwtzXg49EljkKhimDCbZHF9ASHriy47sp6DMQ7f",
	"W/HFuvF1R+7W/qnPVWfuYJNXhbTfn/TYDmK00GCyPbH7nd8lFrcJr/CDhFU2w8AUQpHSZJmBJIESnsBo",
	"9dO/n3Dick4+vqJ/0rCgY/rdcFMRDUM5NHxveryrjcQevW/p9GK/FdzN48zGhA6xX1tavxmKVJ7JU4zN",
	"0xBT71jxIYldu5kQFz2J326bwSeVyYEphM3+ITNl7ECodgFYX9gtNeoM0vOteg9rpkJIUVQFOSZJxjRL",
	"LGjTYeDc6pFMndTfYSp5efLfP2O0FPIXkKnN6Pj4ujqhZrLh6eKmKr5TtVAs2HVg98VxzC33Zip3bgm+",
	"sRLxptVh0FoAPgdjnCU8cSdTPn9eay8ile/LkGz3eMc+pbwv/0hR524K+YNGq40Et6xOfGH9zrUY7brp",
	"A3WNvEu2FxEVFgrTW7+EBaY1W+H/oZtBit1CLBTnOwS4MGXOVm9cu9++8JPKJDlH4Puu+c6jDyS7VPEG",
	"EhIOtpFxBUDBvtQ4HHVQObqf+cVCaGO9VE4U7JZYs+Ll6gvaD1/Ivg8V1G3s5JJZpt/rvNcGEjdG4X52",
	"dLOB0GOZyaOFG7fxW+hEW1qaK5UDk3ikd1rE62lR3cE/zapbmEkzOegV7pv1xzJTEt5Uxdw7zW51u9k/",
	"DL++ryC73dc0vtn2xK6Ldf0nasy4a7WRH6O1sW6Abem8q5N+DdTiXuyJP66SeJUxmcLd6ggJy9MnVkrs",
	"jjC2oWqY3qeWVrsB9tsosK7Xyr6q03VBSaWFXZ0jMS/fD8A06EmFoSE8gDhHc8sbPjFd0jXSEHLhUmmi",
	"pGWJbemImqoslbZtucOzwxtceWbIuT+BXorJr8nCzQ2Xy9qKPgd9KRIgVpHJZtqCDpSLBEILGb4yKVmS",
	"ATkajHY+sFwuB8xtD5ROh+GuGf5y9ur0zflpfDQYDTJb5C48gC7M20X4ciAyHg7NkqUp6IFQQ3dkiOoR",
	"Nm8EdBzSiF6C9s0mfT4YDUYeXZCsFHRMj92SSzSZQ2CYActt9h/8O/UDRDRAN1I643RMfwT7OhxBpH3n",
	"7K4ejUY1FCC9ZW8m48NPxje83nSuNazN7NHh3A+DMMSz6wOnqYqC6RUdU88hSTJIPqNeWGrQGP1herGO",
	"8E++K9xrYPywdPfMyDqiw5I5ZZXK9Kh7qoydujeyMJj/QfHVval5511x3fVfTLTrB4R5942uD+3KNfWL",
	"Ks9XJCRBwsg0tPzE9/zEN/3twELHH7oh5cPF+qKNjv/8PlrkL9PJ7K8t1Nybg4PMiFQKOdx6RDkI4rm7",
	"0mmyHwjUA0PER4b30KztOqBRxcCJkAPypspzEmZmpAAmDZm9nU2xN/ejNfQ/CcCBb7kfMkCEJEthM58d",
	"CZOctJ69amw9optXNsk3uHYwL1uzo2GTj6/DfWfi9KDY751vPTL+h6P4rywVCcmF/EwMSItJFavlZyYg",
	"ZVrmcAjX4jCdATlbuAXCFRj5zBL4IoyNiLBkKfKczKGOKgMyy4CE2of4UgVty68wbzwJk3ilMsDxUwZs",
	"0+I9M/7JxZtKSqqSMCJh6TYH5MwRE6lUGi170xqS8KjrOTODPrv0j6OteRGCu22a9ma2aB/W+r5aOtl6",
	"v7lxiDlkXTdLDQ1M3RxRlbfOEVX5WDliz8j3aWOmIRXGgkZn7ckLPnL4Hw2Ed1BhSAmSh8bmZHR8b6x3",
	"f2rSx7nDkxSQZEwKUyAvza8bHDMvH48ZbEG9SafiEmSdDjuRp8cRqvKG2dMFp73ZE8Oc94Vh4iYDhz1h",
	"a4zwQF6wZ1ixDi7wVbKi44d4HZEgNBr7pEbMocG6Nu6SX8YMmQOmn5AFMb1g9mGca0wWt6uNPQcuPTVj",
	"ggB39wdJe8Cu14YaDNjr4e6MRx4Q8N4xzFeFvOaIOE1tQN/yxsArYZunKnfhJrZRFzpt0wgVS20dN4e3",
	"mSjsHxH8Fo78nzq9xWisxdRm/DUajAajmMPltQ/I9fWeSdUOXkG4erhvwmimi9aPYMllo4Vatc1n0OD+",
	"FwAA//8jhOXt8SsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
