query GetHasuraSettings($appId: uuid!) {
  config(appID: $appId, resolve: false) {
    id: __typename
    __typename
    hasura {
      version
      settings {
        enableAllowList
        enableRemoteSchemaPermissions
        enableConsole
        devMode
        corsDomain
        enabledAPIs
        inferFunctionPermissions
      }
      logs {
        level
      }
      events {
        httpPoolSize
      }
      resources {
        networking {
          ingresses {
            fqdn
          }
        }
      }
    }
  }
}
