name = 'mysvc'
command = [
  "node", "index.js"
]

[image]
image = 'mysvc:dev'

[[ports]]
port = 8000
type = 'http'
publish = true

[resources]
replicas = 1

[resources.compute]
cpu = 62
memory = 128
