name = 'bun-gen'

[image]
image = 'nhost/bun-generator:0.0.3'

[[environment]]
name = 'PEXELS_API_KEY'
value = '{{ secrets.PEXELS_API_KEY }}'

[[environment]]
name = 'SOME_COMPLEX_ENV_VAR'
value = '#asdasd;l;kq23\\n40-0as9d"$\'

[[ports]]
port = 5000
type = 'http'
publish = true

[resources]
replicas = 1

[resources.compute]
cpu = 62
memory = 128
