import { Plus, X } from 'lucide-react';
import { useFieldArray, useFormContext, useFormState, useWatch } from 'react-hook-form';
import { useDialog } from '@/components/common/DialogProvider';
import { FormInput } from '@/components/form/FormInput';
import { Button } from '@/components/ui/v3/button';
import { Label } from '@/components/ui/v3/label';
import {
  MultiSelect,
  MultiSelectContent,
  MultiSelectGroup,
  MultiSelectItem,
  MultiSelectTrigger,
  MultiSelectValue,
} from '@/components/ui/v3/multi-select';
import { createConstraintFormId } from '@/features/orgs/projects/database/dataGrid/components/BaseTableForm/formReferences';
import type {
  DatabaseColumn,
  FormUniqueConstraint,
} from '@/features/orgs/projects/database/dataGrid/types/dataBrowser';

function ConstraintErrorMessage() {
  const { errors } = useFormState({ name: 'uniqueConstraints' });
  const error = errors.uniqueConstraints;
  const message =
    typeof error?.message === 'string'
      ? error.message
      : typeof error?.root?.message === 'string'
        ? error.root.message
        : undefined;

  return message ? (
    <p className="font-medium text-destructive text-sm">{message}</p>
  ) : null;
}

export default function UniqueConstraintEditorSection() {
  const { openAlertDialog } = useDialog();
  const { control, setValue } = useFormContext();
  const { fields, append, remove } = useFieldArray({
    control,
    name: 'uniqueConstraints',
    keyName: 'fieldId',
  });
  const columns = (useWatch({ name: 'columns' }) ?? []) as DatabaseColumn[];
  const constraints = (useWatch({ name: 'uniqueConstraints' }) ??
    []) as FormUniqueConstraint[];
  const availableColumns = columns.filter(({ formReference }) => formReference);

  const updateReferences = (index: number, columnReferences: string[]) => {
    setValue(`uniqueConstraints.${index}.columnReferences`, columnReferences, {
      shouldDirty: true,
      shouldValidate: true,
    });
  };

  return (
    <div className="space-y-4 px-6">
      <p className="text-muted-foreground text-sm">
        UNIQUE constraints may contain one or more columns. Column order is
        preserved.
      </p>

      {fields.map((field, constraintIndex) => {
        const constraint = constraints[constraintIndex];
        const references = constraint?.columnReferences ?? [];

        return (
          <div
            key={field.fieldId}
            className="space-y-3 rounded-md border border-border p-4"
          >
            <div className="flex items-start gap-2">
              <div className="w-full max-w-sm">
                <FormInput
                  control={control}
                  name={`uniqueConstraints.${constraintIndex}.name`}
                  label={constraint?.originalName ? 'Name' : 'Name (optional)'}
                  placeholder="Generated by PostgreSQL when empty"
                  autoComplete="off"
                  className="border-border"
                />
              </div>
              <Button
                type="button"
                variant="outline"
                size="icon"
                className="self-end"
                aria-label="Remove unique constraint"
                onClick={() =>
                  openAlertDialog({
                    title: 'Remove unique constraint?',
                    payload:
                      'This UNIQUE constraint will be removed when you save the table.',
                    props: {
                      primaryButtonText: 'Remove',
                      primaryButtonColor: 'error',
                      onPrimaryAction: () => remove(constraintIndex),
                    },
                  })
                }
              >
                <X className="h-4 w-4" />
              </Button>
            </div>

            <div className="space-y-2">
              <Label htmlFor={`unique-constraint-${constraintIndex}-columns`}>
                Columns
              </Label>
              <MultiSelect
                values={references}
                onValuesChange={(values) =>
                  updateReferences(constraintIndex, values)
                }
              >
                <MultiSelectTrigger
                  id={`unique-constraint-${constraintIndex}-columns`}
                  className="h-10 w-full"
                >
                  <MultiSelectValue placeholder="Select columns" />
                </MultiSelectTrigger>
                <MultiSelectContent>
                  <MultiSelectGroup>
                    {references
                      .filter(
                        (reference) =>
                          !availableColumns.some(
                            ({ formReference }) =>
                              formReference === reference,
                          ),
                      )
                      .map((reference) => (
                        <MultiSelectItem
                          key={reference}
                          value={reference}
                          badgeLabel={`Missing column (${reference})`}
                          disabled
                        >
                          Missing column ({reference})
                        </MultiSelectItem>
                      ))}
                    {availableColumns.map((column) => (
                      <MultiSelectItem
                        key={column.formReference}
                        value={column.formReference!}
                      >
                        {column.name || 'Unnamed column'}
                      </MultiSelectItem>
                    ))}
                  </MultiSelectGroup>
                </MultiSelectContent>
              </MultiSelect>
            </div>
          </div>
        );
      })}

      <ConstraintErrorMessage />

      <Button
        type="button"
        variant="ghost"
        size="sm"
        className="gap-2 text-primary"
        disabled={availableColumns.length === 0}
        onClick={() =>
          append({
            id: createConstraintFormId(),
            name: '',
            columnReferences: [],
          })
        }
      >
        <Plus className="h-4 w-4" />
        Add Unique Constraint
      </Button>
    </div>
  );
}
