query GetConfiguredPreloadLibraries($appId: uuid!) {
  config(appID: $appId, resolve: false) {
    id: __typename
    __typename
    postgres {
      settings {
        sharedPreloadLibraries
      }
    }
  }
}
