// Code generated by MockGen. DO NOT EDIT.
// Source: sms.go
//
// Generated by this command:
//
//	mockgen -package mock -destination mock/sms.go --source=sms.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	sql "github.com/nhost/nhost/services/auth/go/sql"
	gomock "go.uber.org/mock/gomock"
)

// MockGenericSMSProvider is a mock of GenericSMSProvider interface.
type MockGenericSMSProvider struct {
	ctrl     *gomock.Controller
	recorder *MockGenericSMSProviderMockRecorder
	isgomock struct{}
}

// MockGenericSMSProviderMockRecorder is the mock recorder for MockGenericSMSProvider.
type MockGenericSMSProviderMockRecorder struct {
	mock *MockGenericSMSProvider
}

// NewMockGenericSMSProvider creates a new mock instance.
func NewMockGenericSMSProvider(ctrl *gomock.Controller) *MockGenericSMSProvider {
	mock := &MockGenericSMSProvider{ctrl: ctrl}
	mock.recorder = &MockGenericSMSProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenericSMSProvider) EXPECT() *MockGenericSMSProviderMockRecorder {
	return m.recorder
}

// SendSMS mocks base method.
func (m *MockGenericSMSProvider) SendSMS(to, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendSMS", to, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendSMS indicates an expected call of SendSMS.
func (mr *MockGenericSMSProviderMockRecorder) SendSMS(to, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendSMS", reflect.TypeOf((*MockGenericSMSProvider)(nil).SendSMS), to, body)
}

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
	isgomock struct{}
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// GetUserByPhoneNumber mocks base method.
func (m *MockDB) GetUserByPhoneNumber(ctx context.Context, phoneNumber pgtype.Text) (sql.AuthUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByPhoneNumber", ctx, phoneNumber)
	ret0, _ := ret[0].(sql.AuthUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByPhoneNumber indicates an expected call of GetUserByPhoneNumber.
func (mr *MockDBMockRecorder) GetUserByPhoneNumber(ctx, phoneNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByPhoneNumber", reflect.TypeOf((*MockDB)(nil).GetUserByPhoneNumber), ctx, phoneNumber)
}

// VerifySMSOTPAndPromotePhoneNumber mocks base method.
func (m *MockDB) VerifySMSOTPAndPromotePhoneNumber(ctx context.Context, arg sql.VerifySMSOTPAndPromotePhoneNumberParams) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifySMSOTPAndPromotePhoneNumber", ctx, arg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifySMSOTPAndPromotePhoneNumber indicates an expected call of VerifySMSOTPAndPromotePhoneNumber.
func (mr *MockDBMockRecorder) VerifySMSOTPAndPromotePhoneNumber(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifySMSOTPAndPromotePhoneNumber", reflect.TypeOf((*MockDB)(nil).VerifySMSOTPAndPromotePhoneNumber), ctx, arg)
}
