---
on:
  workflow_call:
    inputs:
      VERSION:
        type: string
        required: true
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

name: release
jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.GIT_REF }}
          submodules: true

      - name: Compute common env vars
        id: vars
        run: |
          echo "VERSION=$(make get-version VERSION=${{ inputs.VERSION }})" >> $GITHUB_OUTPUT

      - name: "Get artifacts"
        uses: actions/download-artifact@v4
        with:
          path: ~/artifacts

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Upload docker images
        shell: bash
        run: |
          export VERSION=${{ steps.vars.outputs.VERSION }}
          export CONTAINER_NAME=nhost/cli

          skopeo copy --insecure-policy \
            dir:/home/runner/artifacts/cli-docker-image-$VERSION-linux-amd64 \
            docker-daemon:$CONTAINER_NAME:$VERSION-amd64
          docker push $CONTAINER_NAME:$VERSION-amd64

          skopeo copy --insecure-policy \
            dir:/home/runner/artifacts/cli-docker-image-$VERSION-linux-arm64 \
            docker-daemon:$CONTAINER_NAME:$VERSION-arm64
          docker push $CONTAINER_NAME:$VERSION-arm64

          docker manifest create \
              $CONTAINER_NAME:$VERSION \
              --amend $CONTAINER_NAME:$VERSION-amd64 \
              --amend $CONTAINER_NAME:$VERSION-arm64
          docker manifest push $CONTAINER_NAME:$VERSION

      - name: Upload assets
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export VERSION=${{ steps.vars.outputs.VERSION }}

          mkdir upload

          find ~/artifacts -type f -name "nhost-cli" -exec bash -c 'chmod +x "$0" && mv "$0" "${0//nhost-cli/cli}"' {} \;

          tar cvzf upload/cli-$VERSION-darwin-amd64.tar.gz -C ~/artifacts/cli-$VERSION-darwin-amd64 cli
          tar cvzf upload/cli-$VERSION-darwin-arm64.tar.gz -C ~/artifacts/cli-$VERSION-darwin-arm64 cli
          tar cvzf upload/cli-$VERSION-linux-amd64.tar.gz -C ~/artifacts/cli-$VERSION-linux-amd64 cli
          tar cvzf upload/cli-$VERSION-linux-arm64.tar.gz -C ~/artifacts/cli-$VERSION-linux-arm64 cli

          cd upload
          find . -type f -exec sha256sum {} + > ../checksums.txt
          cd ..

          cat checksums.txt

          gh release upload \
            --clobber "${{ github.ref_name }}" \
            ./upload/* checksums.txt
