query getGraphiteAutoEmbeddingsConfigurations($limit: Int!, $offset: Int!) {
  graphiteAutoEmbeddingsConfigurations(limit: $limit, offset: $offset) {
    id
    name
    model
    schemaName
    tableName
    columnName
    query
    mutation
    createdAt
    updatedAt
  }

  graphiteAutoEmbeddingsConfigurationAggregate {
    aggregate {
      count
    }
  }
}
