mutation updateGraphiteAutoEmbeddingsConfiguration(
  $id: uuid!
  $name: String
  $model: String
  $schemaName: String
  $tableName: String
  $columnName: String
  $query: String
  $mutation: String
) {
  updateGraphiteAutoEmbeddingsConfiguration(
    pk_columns: { id: $id }
    _set: {
      name: $name
      model: $model
      schemaName: $schemaName
      tableName: $tableName
      columnName: $columnName
      query: $query
      mutation: $mutation
    }
  ) {
    id
    name
    model
    schemaName
    tableName
    columnName
    query
    mutation
  }
}
