// Code generated by tools/codegen. DO NOT EDIT.

package auth

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/nhost/nhost/packages/nhost-go/fetch"
)

// AttestationFormat is one of: "packed", "tpm", "android-key", "android-safetynet", "fido-u2f", "apple", "none".
type AttestationFormat string

type AuthenticationExtensionsClientOutputs struct {
	Appid            *bool                       `json:"appid,omitempty"`
	CredProps        *CredentialPropertiesOutput `json:"credProps,omitempty"`
	HmacCreateSecret *bool                       `json:"hmacCreateSecret,omitempty"`
}

type AuthenticatorAssertionResponse struct {
	ClientDataJSON    string  `json:"clientDataJSON"`
	AuthenticatorData string  `json:"authenticatorData"`
	Signature         string  `json:"signature"`
	UserHandle        *string `json:"userHandle,omitempty"`
}

// AuthenticatorAttachment is one of: "platform", "cross-platform".
type AuthenticatorAttachment string

type AuthenticatorAttestationResponse struct {
	ClientDataJSON     string    `json:"clientDataJSON"`
	Transports         *[]string `json:"transports,omitempty"`
	AuthenticatorData  *string   `json:"authenticatorData,omitempty"`
	PublicKey          *string   `json:"publicKey,omitempty"`
	PublicKeyAlgorithm *int      `json:"publicKeyAlgorithm,omitempty"`
	AttestationObject  string    `json:"attestationObject"`
}

type AuthenticatorSelection struct {
	AuthenticatorAttachment *AuthenticatorAttachment     `json:"authenticatorAttachment,omitempty"`
	RequireResidentKey      *bool                        `json:"requireResidentKey,omitempty"`
	ResidentKey             *ResidentKeyRequirement      `json:"residentKey,omitempty"`
	UserVerification        *UserVerificationRequirement `json:"userVerification,omitempty"`
}

// AuthenticatorTransport is one of: "usb", "nfc", "ble", "smart-card", "hybrid", "internal".
type AuthenticatorTransport string

// ConveyancePreference is one of: "none", "indirect", "direct", "enterprise".
type ConveyancePreference string

type CreatePATRequest struct {
	ExpiresAt string          `json:"expiresAt"`
	Metadata  *map[string]any `json:"metadata,omitempty"`
}

type CreatePATResponse struct {
	ID                  string `json:"id"`
	PersonalAccessToken string `json:"personalAccessToken"`
}

type CredentialAssertionResponse struct {
	ID                      string                                 `json:"id"`
	Type                    string                                 `json:"type"`
	RawID                   string                                 `json:"rawId"`
	ClientExtensionResults  *AuthenticationExtensionsClientOutputs `json:"clientExtensionResults,omitempty"`
	AuthenticatorAttachment *string                                `json:"authenticatorAttachment,omitempty"`
	Response                AuthenticatorAssertionResponse         `json:"response"`
}

type CredentialCreationResponse struct {
	ID                      string                                 `json:"id"`
	Type                    string                                 `json:"type"`
	RawID                   string                                 `json:"rawId"`
	ClientExtensionResults  *AuthenticationExtensionsClientOutputs `json:"clientExtensionResults,omitempty"`
	AuthenticatorAttachment *string                                `json:"authenticatorAttachment,omitempty"`
	Response                AuthenticatorAttestationResponse       `json:"response"`
}

type CredentialParameter struct {
	Type CredentialType `json:"type"`
	Alg  int            `json:"alg"`
}

type CredentialPropertiesOutput struct {
	Rk *bool `json:"rk,omitempty"`
}

// CredentialType is one of: "public-key".
type CredentialType string

// ErrorResponseError is one of: "default-role-must-be-in-allowed-roles", "disabled-endpoint", "disabled-user", "user-already-exists", "email-already-verified", "forbidden-anonymous", "internal-server-error", "invalid-email-password", "invalid-request", "locale-not-allowed", "password-too-short", "password-in-hibp-database", "redirectTo-not-allowed", "role-not-allowed", "signup-disabled", "unverified-user", "user-not-anonymous", "invalid-pat", "invalid-refresh-token", "invalid-ticket", "disabled-mfa-totp", "no-totp-secret", "invalid-totp", "mfa-type-not-found", "totp-already-active", "invalid-state", "oauth-token-echange-failed", "oauth-profile-fetch-failed", "oauth-provider-error", "invalid-otp", "otp-too-many-attempts", "cannot-send-sms", "provider-account-already-linked".
type ErrorResponseError string

type ErrorResponse struct {
	Status  int                `json:"status"`
	Message string             `json:"message"`
	Error   ErrorResponseError `json:"error"`
}

// IDTokenProvider is one of: "apple", "google".
type IDTokenProvider string

type Jwk struct {
	Alg string `json:"alg"`
	E   string `json:"e"`
	Kid string `json:"kid"`
	Kty string `json:"kty"`
	N   string `json:"n"`
	Use string `json:"use"`
}

type JwkSet struct {
	Keys []Jwk `json:"keys"`
}

type LinkIDTokenRequest struct {
	Provider IDTokenProvider `json:"provider"`
	IDToken  string          `json:"idToken"`
	Nonce    *string         `json:"nonce,omitempty"`
}

type MFAChallengePayload struct {
	Ticket string `json:"ticket"`
}

// OKResponse is one of: "OK".
type OKResponse string

type OptionsRedirectTo struct {
	RedirectTo *string `json:"redirectTo,omitempty"`
}

type PublicKeyCredentialCreationOptions struct {
	Rp                     RelyingPartyEntity               `json:"rp"`
	User                   UserEntity                       `json:"user"`
	Challenge              string                           `json:"challenge"`
	PubKeyCredParams       []CredentialParameter            `json:"pubKeyCredParams"`
	Timeout                *int                             `json:"timeout,omitempty"`
	ExcludeCredentials     *[]PublicKeyCredentialDescriptor `json:"excludeCredentials,omitempty"`
	AuthenticatorSelection *AuthenticatorSelection          `json:"authenticatorSelection,omitempty"`
	Hints                  *[]PublicKeyCredentialHints      `json:"hints,omitempty"`
	Attestation            *ConveyancePreference            `json:"attestation,omitempty"`
	AttestationFormats     *[]AttestationFormat             `json:"attestationFormats,omitempty"`
	Extensions             *map[string]any                  `json:"extensions,omitempty"`
}

type PublicKeyCredentialDescriptor struct {
	Type       CredentialType            `json:"type"`
	ID         string                    `json:"id"`
	Transports *[]AuthenticatorTransport `json:"transports,omitempty"`
}

// PublicKeyCredentialHints is one of: "security-key", "client-device", "hybrid".
type PublicKeyCredentialHints string

type PublicKeyCredentialRequestOptions struct {
	Challenge        string                           `json:"challenge"`
	Timeout          *int                             `json:"timeout,omitempty"`
	RpID             *string                          `json:"rpId,omitempty"`
	AllowCredentials *[]PublicKeyCredentialDescriptor `json:"allowCredentials,omitempty"`
	UserVerification *UserVerificationRequirement     `json:"userVerification,omitempty"`
	Hints            *[]PublicKeyCredentialHints      `json:"hints,omitempty"`
	Extensions       *map[string]any                  `json:"extensions,omitempty"`
}

type ProviderSession struct {
	AccessToken  string  `json:"accessToken"`
	ExpiresIn    int     `json:"expiresIn"`
	ExpiresAt    string  `json:"expiresAt"`
	RefreshToken *string `json:"refreshToken,omitempty"`
}

type ProviderSpecificParams struct {
	Connection   *string `json:"connection,omitempty"`
	Organization *string `json:"organization,omitempty"`
}

type RefreshProviderTokenRequest struct {
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refreshToken"`
}

type RelyingPartyEntity struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

// ResidentKeyRequirement is one of: "discouraged", "preferred", "required".
type ResidentKeyRequirement string

type Session struct {
	AccessToken          string `json:"accessToken"`
	AccessTokenExpiresIn int    `json:"accessTokenExpiresIn"`
	RefreshTokenID       string `json:"refreshTokenId"`
	RefreshToken         string `json:"refreshToken"`
	User                 *User  `json:"user,omitempty"`
}

type SessionPayload struct {
	Session *Session `json:"session,omitempty"`
}

type SignInAnonymousRequest struct {
	DisplayName *string         `json:"displayName,omitempty"`
	Locale      *string         `json:"locale,omitempty"`
	Metadata    *map[string]any `json:"metadata,omitempty"`
}

type SignInEmailPasswordRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignInEmailPasswordResponse struct {
	Session *Session             `json:"session,omitempty"`
	MFA     *MFAChallengePayload `json:"mfa,omitempty"`
}

type SignInIDTokenRequest struct {
	Provider IDTokenProvider `json:"provider"`
	IDToken  string          `json:"idToken"`
	Nonce    *string         `json:"nonce,omitempty"`
	Options  *SignUpOptions  `json:"options,omitempty"`
}

type SignInMFATOTPRequest struct {
	Ticket string `json:"ticket"`
	OTP    string `json:"otp"`
}

type SignInOTPEmailRequest struct {
	Email   string         `json:"email"`
	Options *SignUpOptions `json:"options,omitempty"`
}

type SignInOTPEmailVerifyRequest struct {
	OTP   string `json:"otp"`
	Email string `json:"email"`
}

type SignInOTPEmailVerifyResponse struct {
	Session *Session `json:"session,omitempty"`
}

type SignInPATRequest struct {
	PersonalAccessToken string `json:"personalAccessToken"`
}

type SignInPasswordlessEmailRequest struct {
	Email         string         `json:"email"`
	Options       *SignUpOptions `json:"options,omitempty"`
	CodeChallenge *string        `json:"codeChallenge,omitempty"`
}

type SignInPasswordlessSMSOTPRequest struct {
	PhoneNumber string `json:"phoneNumber"`
	OTP         string `json:"otp"`
}

type SignInPasswordlessSMSOTPResponse struct {
	Session *Session             `json:"session,omitempty"`
	MFA     *MFAChallengePayload `json:"mfa,omitempty"`
}

type SignInPasswordlessSMSRequest struct {
	PhoneNumber string         `json:"phoneNumber"`
	Options     *SignUpOptions `json:"options,omitempty"`
}

type SignUpPasswordlessEmailRequest struct {
	Email         string         `json:"email"`
	Options       *SignUpOptions `json:"options,omitempty"`
	CodeChallenge *string        `json:"codeChallenge,omitempty"`
}

type SignUpOTPEmailRequest struct {
	Email   string         `json:"email"`
	Options *SignUpOptions `json:"options,omitempty"`
}

type SignUpPasswordlessSMSRequest struct {
	PhoneNumber string         `json:"phoneNumber"`
	Options     *SignUpOptions `json:"options,omitempty"`
}

type SignUpIDTokenRequest struct {
	Provider IDTokenProvider `json:"provider"`
	IDToken  string          `json:"idToken"`
	Nonce    *string         `json:"nonce,omitempty"`
	Options  *SignUpOptions  `json:"options,omitempty"`
}

type SignInWebAuthnRequest struct {
	Email *string `json:"email,omitempty"`
}

type SignInWebAuthnVerifyRequest struct {
	Email      *string                     `json:"email,omitempty"`
	Credential CredentialAssertionResponse `json:"credential"`
}

type SignOutRequest struct {
	RefreshToken *string `json:"refreshToken,omitempty"`
	All          *bool   `json:"all,omitempty"`
}

type SignUpEmailPasswordRequest struct {
	Email         string         `json:"email"`
	Password      string         `json:"password"`
	Options       *SignUpOptions `json:"options,omitempty"`
	CodeChallenge *string        `json:"codeChallenge,omitempty"`
}

type SignUpOptions struct {
	AllowedRoles *[]string       `json:"allowedRoles,omitempty"`
	DefaultRole  *string         `json:"defaultRole,omitempty"`
	DisplayName  *string         `json:"displayName,omitempty"`
	Locale       *string         `json:"locale,omitempty"`
	Metadata     *map[string]any `json:"metadata,omitempty"`
	RedirectTo   *string         `json:"redirectTo,omitempty"`
}

type SignUpWebAuthnRequest struct {
	Email   string         `json:"email"`
	Options *SignUpOptions `json:"options,omitempty"`
}

type SignUpWebAuthnVerifyRequest struct {
	Credential    CredentialCreationResponse `json:"credential"`
	Options       *SignUpOptions             `json:"options,omitempty"`
	Nickname      *string                    `json:"nickname,omitempty"`
	CodeChallenge *string                    `json:"codeChallenge,omitempty"`
}

type TokenExchangeRequest struct {
	Code         string `json:"code"`
	CodeVerifier string `json:"codeVerifier"`
}

type TOTPGenerateResponse struct {
	ImageURL   string `json:"imageUrl"`
	TOTPSecret string `json:"totpSecret"`
}

type URLEncodedBase64 = string

type User struct {
	AvatarURL           string          `json:"avatarUrl"`
	CreatedAt           string          `json:"createdAt"`
	DefaultRole         string          `json:"defaultRole"`
	DisplayName         string          `json:"displayName"`
	Email               *string         `json:"email,omitempty"`
	EmailVerified       bool            `json:"emailVerified"`
	ID                  string          `json:"id"`
	IsAnonymous         bool            `json:"isAnonymous"`
	Locale              string          `json:"locale"`
	Metadata            *map[string]any `json:"metadata"`
	PhoneNumber         *string         `json:"phoneNumber,omitempty"`
	PhoneNumberVerified bool            `json:"phoneNumberVerified"`
	Roles               []string        `json:"roles"`
	ActiveMFAType       *string         `json:"activeMfaType,omitempty"`
}

// UserDeanonymizeRequestSignInMethod is one of: "email-password", "passwordless".
type UserDeanonymizeRequestSignInMethod string

type UserDeanonymizeRequest struct {
	SignInMethod  UserDeanonymizeRequestSignInMethod `json:"signInMethod"`
	Email         string                             `json:"email"`
	Password      *string                            `json:"password,omitempty"`
	Connection    *string                            `json:"connection,omitempty"`
	Options       *SignUpOptions                     `json:"options,omitempty"`
	CodeChallenge *string                            `json:"codeChallenge,omitempty"`
}

type UserEmailChangeRequest struct {
	NewEmail      string             `json:"newEmail"`
	Options       *OptionsRedirectTo `json:"options,omitempty"`
	CodeChallenge *string            `json:"codeChallenge,omitempty"`
}

type UserEmailSendVerificationEmailRequest struct {
	Email         string             `json:"email"`
	Options       *OptionsRedirectTo `json:"options,omitempty"`
	CodeChallenge *string            `json:"codeChallenge,omitempty"`
}

type UserEntity struct {
	Name        string `json:"name"`
	DisplayName string `json:"displayName"`
	ID          string `json:"id"`
}

// UserMFARequestActiveMFAType is one of: "totp", "".
type UserMFARequestActiveMFAType string

type UserMFARequest struct {
	Code          string                       `json:"code"`
	ActiveMFAType *UserMFARequestActiveMFAType `json:"activeMfaType,omitempty"`
}

type UserPasswordRequest struct {
	NewPassword string  `json:"newPassword"`
	Ticket      *string `json:"ticket,omitempty"`
}

type UserPasswordResetRequest struct {
	Email         string             `json:"email"`
	Options       *OptionsRedirectTo `json:"options,omitempty"`
	CodeChallenge *string            `json:"codeChallenge,omitempty"`
}

// UserVerificationRequirement is one of: "required", "preferred", "discouraged".
type UserVerificationRequirement string

type VerifyAddSecurityKeyRequest struct {
	Credential CredentialCreationResponse `json:"credential"`
	Nickname   *string                    `json:"nickname,omitempty"`
}

type VerifyAddSecurityKeyResponse struct {
	ID       string  `json:"id"`
	Nickname *string `json:"nickname,omitempty"`
}

type VerifyTokenRequest struct {
	Token *string `json:"token,omitempty"`
}

type OAuth2ErrorResponse struct {
	Error            string  `json:"error"`
	ErrorDescription *string `json:"error_description,omitempty"`
}

type OAuth2DiscoveryResponse struct {
	Issuer                                     string    `json:"issuer"`
	AuthorizationEndpoint                      string    `json:"authorization_endpoint"`
	TokenEndpoint                              string    `json:"token_endpoint"`
	UserinfoEndpoint                           *string   `json:"userinfo_endpoint,omitempty"`
	JwksURI                                    string    `json:"jwks_uri"`
	RevocationEndpoint                         *string   `json:"revocation_endpoint,omitempty"`
	IntrospectionEndpoint                      *string   `json:"introspection_endpoint,omitempty"`
	ScopesSupported                            *[]string `json:"scopes_supported,omitempty"`
	ResponseTypesSupported                     []string  `json:"response_types_supported"`
	GrantTypesSupported                        *[]string `json:"grant_types_supported,omitempty"`
	SubjectTypesSupported                      *[]string `json:"subject_types_supported,omitempty"`
	IDTokenSigningAlgValuesSupported           *[]string `json:"id_token_signing_alg_values_supported,omitempty"`
	TokenEndpointAuthMethodsSupported          *[]string `json:"token_endpoint_auth_methods_supported,omitempty"`
	CodeChallengeMethodsSupported              *[]string `json:"code_challenge_methods_supported,omitempty"`
	ClaimsSupported                            *[]string `json:"claims_supported,omitempty"`
	RequestParameterSupported                  *bool     `json:"request_parameter_supported,omitempty"`
	AuthorizationResponseIssParameterSupported *bool     `json:"authorization_response_iss_parameter_supported,omitempty"`
	ClientIDMetadataDocumentSupported          *bool     `json:"client_id_metadata_document_supported,omitempty"`
}

// OAuth2TokenRequestGrantType is one of: "authorization_code", "refresh_token".
type OAuth2TokenRequestGrantType string

type OAuth2TokenRequest struct {
	GrantType    OAuth2TokenRequestGrantType `json:"grant_type"`
	Code         *string                     `json:"code,omitempty"`
	RedirectURI  *string                     `json:"redirect_uri,omitempty"`
	ClientID     *string                     `json:"client_id,omitempty"`
	ClientSecret *string                     `json:"client_secret,omitempty"`
	CodeVerifier *string                     `json:"code_verifier,omitempty"`
	RefreshToken *string                     `json:"refresh_token,omitempty"`
	Resource     *string                     `json:"resource,omitempty"`
}

type OAuth2TokenResponse struct {
	AccessToken  string  `json:"access_token"`
	TokenType    string  `json:"token_type"`
	ExpiresIn    int     `json:"expires_in"`
	RefreshToken *string `json:"refresh_token,omitempty"`
	IDToken      *string `json:"id_token,omitempty"`
	Scope        *string `json:"scope,omitempty"`
}

type OAuth2UserinfoResponse struct {
	Sub                 string  `json:"sub"`
	Name                *string `json:"name,omitempty"`
	Email               *string `json:"email,omitempty"`
	EmailVerified       *bool   `json:"email_verified,omitempty"`
	Picture             *string `json:"picture,omitempty"`
	Locale              *string `json:"locale,omitempty"`
	PhoneNumber         *string `json:"phone_number,omitempty"`
	PhoneNumberVerified *bool   `json:"phone_number_verified,omitempty"`
}

type OAuth2jwksResponse struct {
	Keys []Jwk `json:"keys"`
}

// OAuth2RevokeRequestTokenTypeHint is one of: "access_token", "refresh_token".
type OAuth2RevokeRequestTokenTypeHint string

type OAuth2RevokeRequest struct {
	Token         string                            `json:"token"`
	TokenTypeHint *OAuth2RevokeRequestTokenTypeHint `json:"token_type_hint,omitempty"`
	ClientID      *string                           `json:"client_id,omitempty"`
	ClientSecret  *string                           `json:"client_secret,omitempty"`
}

// OAuth2IntrospectRequestTokenTypeHint is one of: "access_token", "refresh_token".
type OAuth2IntrospectRequestTokenTypeHint string

type OAuth2IntrospectRequest struct {
	Token         string                                `json:"token"`
	TokenTypeHint *OAuth2IntrospectRequestTokenTypeHint `json:"token_type_hint,omitempty"`
	ClientID      *string                               `json:"client_id,omitempty"`
	ClientSecret  *string                               `json:"client_secret,omitempty"`
}

type OAuth2IntrospectResponse struct {
	Active    bool    `json:"active"`
	Scope     *string `json:"scope,omitempty"`
	ClientID  *string `json:"client_id,omitempty"`
	Sub       *string `json:"sub,omitempty"`
	Exp       *int    `json:"exp,omitempty"`
	Iat       *int    `json:"iat,omitempty"`
	Iss       *string `json:"iss,omitempty"`
	TokenType *string `json:"token_type,omitempty"`
}

type OAuth2LoginResponse struct {
	RequestID   string   `json:"requestId"`
	ClientID    string   `json:"clientId"`
	Scopes      []string `json:"scopes"`
	RedirectURI string   `json:"redirectUri"`
}

type OAuth2LoginRequest struct {
	RequestID string `json:"requestId"`
}

type OAuth2LoginCompleteResponse struct {
	RedirectURI string `json:"redirectUri"`
}

type RedirectToQuery = string

// SignInProvider is one of: "apple", "github", "google", "linkedin", "discord", "spotify", "twitch", "gitlab", "bitbucket", "workos", "azuread", "entraid", "strava", "facebook", "windowslive", "twitter".
type SignInProvider string

type TicketQuery = string

// TicketTypeQuery is one of: "emailVerify", "emailConfirmChange", "signinPasswordless", "passwordReset".
type TicketTypeQuery string

type GetVersionResponse200 struct {
	Version string `json:"version"`
}

// GetCodeChallengeMethod is one of: "S256".
type GetCodeChallengeMethod string

type Oauth2AuthorizePostBody struct {
	ClientID            string  `json:"client_id"`
	RedirectURI         string  `json:"redirect_uri"`
	ResponseType        string  `json:"response_type"`
	Scope               *string `json:"scope,omitempty"`
	State               *string `json:"state,omitempty"`
	Nonce               *string `json:"nonce,omitempty"`
	CodeChallenge       *string `json:"code_challenge,omitempty"`
	CodeChallengeMethod *string `json:"code_challenge_method,omitempty"`
	Resource            *string `json:"resource,omitempty"`
	Prompt              *string `json:"prompt,omitempty"`
}

type SignInProviderParams struct {
	AllowedRoles           *[]string               `json:"allowedRoles,omitempty"`
	DefaultRole            *string                 `json:"defaultRole,omitempty"`
	DisplayName            *string                 `json:"displayName,omitempty"`
	Locale                 *string                 `json:"locale,omitempty"`
	Metadata               *map[string]any         `json:"metadata,omitempty"`
	RedirectTo             *string                 `json:"redirectTo,omitempty"`
	Connect                *string                 `json:"connect,omitempty"`
	State                  *string                 `json:"state,omitempty"`
	ProviderSpecificParams *ProviderSpecificParams `json:"providerSpecificParams,omitempty"`
	CodeChallenge          *string                 `json:"codeChallenge,omitempty"`
}

func (p *SignInProviderParams) toQuery() url.Values {
	q := url.Values{}
	if p.AllowedRoles != nil {
		{
			parts := make([]string, 0, len(*p.AllowedRoles))
			for _, item := range *p.AllowedRoles {
				parts = append(parts, fmt.Sprint(item))
			}
			q.Set("allowedRoles", strings.Join(parts, ","))
		}
	}
	if p.DefaultRole != nil {
		q.Set("defaultRole", fmt.Sprint(*p.DefaultRole))
	}
	if p.DisplayName != nil {
		q.Set("displayName", fmt.Sprint(*p.DisplayName))
	}
	if p.Locale != nil {
		q.Set("locale", fmt.Sprint(*p.Locale))
	}
	if p.Metadata != nil {
		{
			encoded, _ := json.Marshal(*p.Metadata)
			q.Set("metadata", string(encoded))
		}
	}
	if p.RedirectTo != nil {
		q.Set("redirectTo", fmt.Sprint(*p.RedirectTo))
	}
	if p.Connect != nil {
		q.Set("connect", fmt.Sprint(*p.Connect))
	}
	if p.State != nil {
		q.Set("state", fmt.Sprint(*p.State))
	}
	if p.ProviderSpecificParams != nil {
		{
			encoded, _ := json.Marshal(*p.ProviderSpecificParams)
			var fields map[string]any
			if json.Unmarshal(encoded, &fields) == nil {
				for k, v := range fields {
					q.Add(k, fmt.Sprint(v))
				}
			}
		}
	}
	if p.CodeChallenge != nil {
		q.Set("codeChallenge", fmt.Sprint(*p.CodeChallenge))
	}
	return q
}

type SignUpProviderParams struct {
	AllowedRoles           *[]string               `json:"allowedRoles,omitempty"`
	DefaultRole            *string                 `json:"defaultRole,omitempty"`
	DisplayName            *string                 `json:"displayName,omitempty"`
	Locale                 *string                 `json:"locale,omitempty"`
	Metadata               *map[string]any         `json:"metadata,omitempty"`
	RedirectTo             *string                 `json:"redirectTo,omitempty"`
	State                  *string                 `json:"state,omitempty"`
	ProviderSpecificParams *ProviderSpecificParams `json:"providerSpecificParams,omitempty"`
	CodeChallenge          *string                 `json:"codeChallenge,omitempty"`
}

func (p *SignUpProviderParams) toQuery() url.Values {
	q := url.Values{}
	if p.AllowedRoles != nil {
		{
			parts := make([]string, 0, len(*p.AllowedRoles))
			for _, item := range *p.AllowedRoles {
				parts = append(parts, fmt.Sprint(item))
			}
			q.Set("allowedRoles", strings.Join(parts, ","))
		}
	}
	if p.DefaultRole != nil {
		q.Set("defaultRole", fmt.Sprint(*p.DefaultRole))
	}
	if p.DisplayName != nil {
		q.Set("displayName", fmt.Sprint(*p.DisplayName))
	}
	if p.Locale != nil {
		q.Set("locale", fmt.Sprint(*p.Locale))
	}
	if p.Metadata != nil {
		{
			encoded, _ := json.Marshal(*p.Metadata)
			q.Set("metadata", string(encoded))
		}
	}
	if p.RedirectTo != nil {
		q.Set("redirectTo", fmt.Sprint(*p.RedirectTo))
	}
	if p.State != nil {
		q.Set("state", fmt.Sprint(*p.State))
	}
	if p.ProviderSpecificParams != nil {
		{
			encoded, _ := json.Marshal(*p.ProviderSpecificParams)
			var fields map[string]any
			if json.Unmarshal(encoded, &fields) == nil {
				for k, v := range fields {
					q.Add(k, fmt.Sprint(v))
				}
			}
		}
	}
	if p.CodeChallenge != nil {
		q.Set("codeChallenge", fmt.Sprint(*p.CodeChallenge))
	}
	return q
}

type VerifyTicketParams struct {
	Ticket        TicketQuery      `json:"ticket"`
	Type          *TicketTypeQuery `json:"type,omitempty"`
	RedirectTo    RedirectToQuery  `json:"redirectTo"`
	CodeChallenge *string          `json:"codeChallenge,omitempty"`
}

func (p *VerifyTicketParams) toQuery() url.Values {
	q := url.Values{}
	q.Set("ticket", fmt.Sprint(p.Ticket))
	if p.Type != nil {
		q.Set("type", fmt.Sprint(*p.Type))
	}
	q.Set("redirectTo", fmt.Sprint(p.RedirectTo))
	if p.CodeChallenge != nil {
		q.Set("codeChallenge", fmt.Sprint(*p.CodeChallenge))
	}
	return q
}

type Oauth2AuthorizeParams struct {
	ClientID            string                  `json:"client_id"`
	RedirectURI         string                  `json:"redirect_uri"`
	ResponseType        string                  `json:"response_type"`
	Scope               *string                 `json:"scope,omitempty"`
	State               *string                 `json:"state,omitempty"`
	Nonce               *string                 `json:"nonce,omitempty"`
	CodeChallenge       *string                 `json:"code_challenge,omitempty"`
	CodeChallengeMethod *GetCodeChallengeMethod `json:"code_challenge_method,omitempty"`
	Resource            *string                 `json:"resource,omitempty"`
	Prompt              *string                 `json:"prompt,omitempty"`
}

func (p *Oauth2AuthorizeParams) toQuery() url.Values {
	q := url.Values{}
	q.Set("client_id", fmt.Sprint(p.ClientID))
	q.Set("redirect_uri", fmt.Sprint(p.RedirectURI))
	q.Set("response_type", fmt.Sprint(p.ResponseType))
	if p.Scope != nil {
		q.Set("scope", fmt.Sprint(*p.Scope))
	}
	if p.State != nil {
		q.Set("state", fmt.Sprint(*p.State))
	}
	if p.Nonce != nil {
		q.Set("nonce", fmt.Sprint(*p.Nonce))
	}
	if p.CodeChallenge != nil {
		q.Set("code_challenge", fmt.Sprint(*p.CodeChallenge))
	}
	if p.CodeChallengeMethod != nil {
		q.Set("code_challenge_method", fmt.Sprint(*p.CodeChallengeMethod))
	}
	if p.Resource != nil {
		q.Set("resource", fmt.Sprint(*p.Resource))
	}
	if p.Prompt != nil {
		q.Set("prompt", fmt.Sprint(*p.Prompt))
	}
	return q
}

type Oauth2LoginGetParams struct {
	RequestID string `json:"request_id"`
}

func (p *Oauth2LoginGetParams) toQuery() url.Values {
	q := url.Values{}
	q.Set("request_id", fmt.Sprint(p.RequestID))
	return q
}

// Client is a generated API client backed by an *http.Client and a middleware chain.
type Client struct {
	BaseURL        string
	chainFunctions []fetch.ChainFunction
	httpClient     *http.Client
	fetch          fetch.FetchFunc
}

// NewClient creates a new API client.
func NewClient(
	baseURL string,
	chainFunctions []fetch.ChainFunction,
	httpClient *http.Client,
) *Client {
	if httpClient == nil {
		httpClient = &http.Client{}
	}

	c := &Client{
		BaseURL:        baseURL,
		chainFunctions: append([]fetch.ChainFunction{}, chainFunctions...),
		httpClient:     httpClient,
	}
	c.fetch = fetch.CreateEnhancedFetch(c.httpClient, c.chainFunctions)

	return c
}

// PushChainFunction appends a middleware chain function and rebuilds the pipeline.
func (c *Client) PushChainFunction(cf fetch.ChainFunction) {
	c.chainFunctions = append(c.chainFunctions, cf)
	c.fetch = fetch.CreateEnhancedFetch(c.httpClient, c.chainFunctions)
}

// GetJwKs performs GET /.well-known/jwks.json.
func (c *Client) GetJwKs(
	ctx context.Context,
	headers http.Header,
) (*fetch.FetchResponse[JwkSet], error) {
	u := fmt.Sprintf("%s/.well-known/jwks.json", c.BaseURL)
	req, err := http.NewRequestWithContext(ctx, "GET", u, nil)
	if err != nil {
		return nil, err
	}
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload JwkSet
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[JwkSet]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// ElevateWebAuthn performs POST /elevate/webauthn.
func (c *Client) ElevateWebAuthn(
	ctx context.Context,
	headers http.Header,
) (*fetch.FetchResponse[PublicKeyCredentialRequestOptions], error) {
	u := fmt.Sprintf("%s/elevate/webauthn", c.BaseURL)
	req, err := http.NewRequestWithContext(ctx, "POST", u, nil)
	if err != nil {
		return nil, err
	}
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload PublicKeyCredentialRequestOptions
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[PublicKeyCredentialRequestOptions]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// VerifyElevateWebAuthn performs POST /elevate/webauthn/verify.
func (c *Client) VerifyElevateWebAuthn(
	ctx context.Context,
	body SignInWebAuthnVerifyRequest,
	headers http.Header,
) (*fetch.FetchResponse[SessionPayload], error) {
	u := fmt.Sprintf("%s/elevate/webauthn/verify", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload SessionPayload
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[SessionPayload]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// HealthCheckGet performs GET /healthz.
func (c *Client) HealthCheckGet(
	ctx context.Context,
	headers http.Header,
) (*fetch.FetchResponse[OKResponse], error) {
	u := fmt.Sprintf("%s/healthz", c.BaseURL)
	req, err := http.NewRequestWithContext(ctx, "GET", u, nil)
	if err != nil {
		return nil, err
	}
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OKResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OKResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// HealthCheckHead performs HEAD /healthz.
func (c *Client) HealthCheckHead(
	ctx context.Context,
	headers http.Header,
) (*fetch.FetchResponse[json.RawMessage], error) {
	u := fmt.Sprintf("%s/healthz", c.BaseURL)
	req, err := http.NewRequestWithContext(ctx, "HEAD", u, nil)
	if err != nil {
		return nil, err
	}
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload json.RawMessage
	return &fetch.FetchResponse[json.RawMessage]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// LinkIDToken performs POST /link/idtoken.
func (c *Client) LinkIDToken(
	ctx context.Context,
	body LinkIDTokenRequest,
	headers http.Header,
) (*fetch.FetchResponse[OKResponse], error) {
	u := fmt.Sprintf("%s/link/idtoken", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OKResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OKResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// ChangeUserMFA performs GET /mfa/totp/generate.
func (c *Client) ChangeUserMFA(
	ctx context.Context,
	headers http.Header,
) (*fetch.FetchResponse[TOTPGenerateResponse], error) {
	u := fmt.Sprintf("%s/mfa/totp/generate", c.BaseURL)
	req, err := http.NewRequestWithContext(ctx, "GET", u, nil)
	if err != nil {
		return nil, err
	}
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload TOTPGenerateResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[TOTPGenerateResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// CreatePAT performs POST /pat.
func (c *Client) CreatePAT(
	ctx context.Context,
	body CreatePATRequest,
	headers http.Header,
) (*fetch.FetchResponse[CreatePATResponse], error) {
	u := fmt.Sprintf("%s/pat", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload CreatePATResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[CreatePATResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// SignInAnonymous performs POST /signin/anonymous.
func (c *Client) SignInAnonymous(
	ctx context.Context,
	body *SignInAnonymousRequest,
	headers http.Header,
) (*fetch.FetchResponse[SessionPayload], error) {
	u := fmt.Sprintf("%s/signin/anonymous", c.BaseURL)
	// The body is optional: when nil, send no body at all rather than the JSON
	// literal "null" (which json.Marshal(nil) would produce), and omit the
	// Content-Type header so the server treats the payload as absent.
	var req *http.Request
	var err error
	if body != nil {
		rawBody, mErr := json.Marshal(body)
		if mErr != nil {
			return nil, mErr
		}
		req, err = http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	} else {
		req, err = http.NewRequestWithContext(ctx, "POST", u, nil)
	}
	if err != nil {
		return nil, err
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload SessionPayload
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[SessionPayload]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// SignInEmailPassword performs POST /signin/email-password.
func (c *Client) SignInEmailPassword(
	ctx context.Context,
	body SignInEmailPasswordRequest,
	headers http.Header,
) (*fetch.FetchResponse[SignInEmailPasswordResponse], error) {
	u := fmt.Sprintf("%s/signin/email-password", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload SignInEmailPasswordResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[SignInEmailPasswordResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// SignInIDToken performs POST /signin/idtoken.
func (c *Client) SignInIDToken(
	ctx context.Context,
	body SignInIDTokenRequest,
	headers http.Header,
) (*fetch.FetchResponse[SessionPayload], error) {
	u := fmt.Sprintf("%s/signin/idtoken", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload SessionPayload
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[SessionPayload]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// VerifySignInMFATOTP performs POST /signin/mfa/totp.
func (c *Client) VerifySignInMFATOTP(
	ctx context.Context,
	body SignInMFATOTPRequest,
	headers http.Header,
) (*fetch.FetchResponse[SessionPayload], error) {
	u := fmt.Sprintf("%s/signin/mfa/totp", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload SessionPayload
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[SessionPayload]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// SignInOTPEmail performs POST /signin/otp/email.
func (c *Client) SignInOTPEmail(
	ctx context.Context,
	body SignInOTPEmailRequest,
	headers http.Header,
) (*fetch.FetchResponse[OKResponse], error) {
	u := fmt.Sprintf("%s/signin/otp/email", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OKResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OKResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// VerifySignInOTPEmail performs POST /signin/otp/email/verify.
func (c *Client) VerifySignInOTPEmail(
	ctx context.Context,
	body SignInOTPEmailVerifyRequest,
	headers http.Header,
) (*fetch.FetchResponse[SignInOTPEmailVerifyResponse], error) {
	u := fmt.Sprintf("%s/signin/otp/email/verify", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload SignInOTPEmailVerifyResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[SignInOTPEmailVerifyResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// SignInPasswordlessEmail performs POST /signin/passwordless/email.
func (c *Client) SignInPasswordlessEmail(
	ctx context.Context,
	body SignInPasswordlessEmailRequest,
	headers http.Header,
) (*fetch.FetchResponse[OKResponse], error) {
	u := fmt.Sprintf("%s/signin/passwordless/email", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OKResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OKResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// SignInPasswordlessSMS performs POST /signin/passwordless/sms.
func (c *Client) SignInPasswordlessSMS(
	ctx context.Context,
	body SignInPasswordlessSMSRequest,
	headers http.Header,
) (*fetch.FetchResponse[OKResponse], error) {
	u := fmt.Sprintf("%s/signin/passwordless/sms", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OKResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OKResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// VerifySignInPasswordlessSMS performs POST /signin/passwordless/sms/otp.
func (c *Client) VerifySignInPasswordlessSMS(
	ctx context.Context,
	body SignInPasswordlessSMSOTPRequest,
	headers http.Header,
) (*fetch.FetchResponse[SignInPasswordlessSMSOTPResponse], error) {
	u := fmt.Sprintf("%s/signin/passwordless/sms/otp", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload SignInPasswordlessSMSOTPResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[SignInPasswordlessSMSOTPResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// SignInPAT performs POST /signin/pat.
func (c *Client) SignInPAT(
	ctx context.Context,
	body SignInPATRequest,
	headers http.Header,
) (*fetch.FetchResponse[SessionPayload], error) {
	u := fmt.Sprintf("%s/signin/pat", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload SessionPayload
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[SessionPayload]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// SignInProviderURL builds the URL for GET /signin/provider/%s without following the redirect.
func (c *Client) SignInProviderURL(provider string, params *SignInProviderParams,
) string {
	u := fmt.Sprintf("%s/signin/provider/%s", c.BaseURL, provider)
	if params != nil {
		if q := params.toQuery(); len(q) > 0 {
			u += "?" + q.Encode()
		}
	}
	return u
}

// GetProviderTokens performs GET /signin/provider/%s/callback/tokens.
func (c *Client) GetProviderTokens(
	ctx context.Context,
	provider string,
	headers http.Header,
) (*fetch.FetchResponse[ProviderSession], error) {
	u := fmt.Sprintf("%s/signin/provider/%s/callback/tokens", c.BaseURL, provider)
	req, err := http.NewRequestWithContext(ctx, "GET", u, nil)
	if err != nil {
		return nil, err
	}
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload ProviderSession
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[ProviderSession]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// SignInWebAuthn performs POST /signin/webauthn.
func (c *Client) SignInWebAuthn(
	ctx context.Context,
	body *SignInWebAuthnRequest,
	headers http.Header,
) (*fetch.FetchResponse[PublicKeyCredentialRequestOptions], error) {
	u := fmt.Sprintf("%s/signin/webauthn", c.BaseURL)
	// The body is optional: when nil, send no body at all rather than the JSON
	// literal "null" (which json.Marshal(nil) would produce), and omit the
	// Content-Type header so the server treats the payload as absent.
	var req *http.Request
	var err error
	if body != nil {
		rawBody, mErr := json.Marshal(body)
		if mErr != nil {
			return nil, mErr
		}
		req, err = http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	} else {
		req, err = http.NewRequestWithContext(ctx, "POST", u, nil)
	}
	if err != nil {
		return nil, err
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload PublicKeyCredentialRequestOptions
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[PublicKeyCredentialRequestOptions]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// VerifySignInWebAuthn performs POST /signin/webauthn/verify.
func (c *Client) VerifySignInWebAuthn(
	ctx context.Context,
	body SignInWebAuthnVerifyRequest,
	headers http.Header,
) (*fetch.FetchResponse[SessionPayload], error) {
	u := fmt.Sprintf("%s/signin/webauthn/verify", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload SessionPayload
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[SessionPayload]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// SignOut performs POST /signout.
func (c *Client) SignOut(
	ctx context.Context,
	body SignOutRequest,
	headers http.Header,
) (*fetch.FetchResponse[OKResponse], error) {
	u := fmt.Sprintf("%s/signout", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OKResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OKResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// SignUpEmailPassword performs POST /signup/email-password.
func (c *Client) SignUpEmailPassword(
	ctx context.Context,
	body SignUpEmailPasswordRequest,
	headers http.Header,
) (*fetch.FetchResponse[SessionPayload], error) {
	u := fmt.Sprintf("%s/signup/email-password", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload SessionPayload
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[SessionPayload]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// SignUpWebAuthn performs POST /signup/webauthn.
func (c *Client) SignUpWebAuthn(
	ctx context.Context,
	body SignUpWebAuthnRequest,
	headers http.Header,
) (*fetch.FetchResponse[PublicKeyCredentialCreationOptions], error) {
	u := fmt.Sprintf("%s/signup/webauthn", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload PublicKeyCredentialCreationOptions
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[PublicKeyCredentialCreationOptions]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// VerifySignUpWebAuthn performs POST /signup/webauthn/verify.
func (c *Client) VerifySignUpWebAuthn(
	ctx context.Context,
	body SignUpWebAuthnVerifyRequest,
	headers http.Header,
) (*fetch.FetchResponse[SessionPayload], error) {
	u := fmt.Sprintf("%s/signup/webauthn/verify", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload SessionPayload
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[SessionPayload]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// SignUpPasswordlessEmail performs POST /signup/passwordless/email.
func (c *Client) SignUpPasswordlessEmail(
	ctx context.Context,
	body SignUpPasswordlessEmailRequest,
	headers http.Header,
) (*fetch.FetchResponse[OKResponse], error) {
	u := fmt.Sprintf("%s/signup/passwordless/email", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OKResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OKResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// SignUpOTPEmail performs POST /signup/otp/email.
func (c *Client) SignUpOTPEmail(
	ctx context.Context,
	body SignUpOTPEmailRequest,
	headers http.Header,
) (*fetch.FetchResponse[OKResponse], error) {
	u := fmt.Sprintf("%s/signup/otp/email", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OKResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OKResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// SignUpPasswordlessSMS performs POST /signup/passwordless/sms.
func (c *Client) SignUpPasswordlessSMS(
	ctx context.Context,
	body SignUpPasswordlessSMSRequest,
	headers http.Header,
) (*fetch.FetchResponse[OKResponse], error) {
	u := fmt.Sprintf("%s/signup/passwordless/sms", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OKResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OKResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// SignUpIDToken performs POST /signup/idtoken.
func (c *Client) SignUpIDToken(
	ctx context.Context,
	body SignUpIDTokenRequest,
	headers http.Header,
) (*fetch.FetchResponse[SessionPayload], error) {
	u := fmt.Sprintf("%s/signup/idtoken", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload SessionPayload
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[SessionPayload]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// SignUpProviderURL builds the URL for GET /signup/provider/%s without following the redirect.
func (c *Client) SignUpProviderURL(provider string, params *SignUpProviderParams,
) string {
	u := fmt.Sprintf("%s/signup/provider/%s", c.BaseURL, provider)
	if params != nil {
		if q := params.toQuery(); len(q) > 0 {
			u += "?" + q.Encode()
		}
	}
	return u
}

// RefreshToken performs POST /token.
func (c *Client) RefreshToken(
	ctx context.Context,
	body RefreshTokenRequest,
	headers http.Header,
) (*fetch.FetchResponse[Session], error) {
	u := fmt.Sprintf("%s/token", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload Session
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[Session]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// RefreshProviderToken performs POST /token/provider/%s.
func (c *Client) RefreshProviderToken(
	ctx context.Context,
	provider string,
	body RefreshProviderTokenRequest,
	headers http.Header,
) (*fetch.FetchResponse[ProviderSession], error) {
	u := fmt.Sprintf("%s/token/provider/%s", c.BaseURL, provider)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload ProviderSession
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[ProviderSession]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// VerifyToken performs POST /token/verify.
func (c *Client) VerifyToken(
	ctx context.Context,
	body *VerifyTokenRequest,
	headers http.Header,
) (*fetch.FetchResponse[string], error) {
	u := fmt.Sprintf("%s/token/verify", c.BaseURL)
	// The body is optional: when nil, send no body at all rather than the JSON
	// literal "null" (which json.Marshal(nil) would produce), and omit the
	// Content-Type header so the server treats the payload as absent.
	var req *http.Request
	var err error
	if body != nil {
		rawBody, mErr := json.Marshal(body)
		if mErr != nil {
			return nil, mErr
		}
		req, err = http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	} else {
		req, err = http.NewRequestWithContext(ctx, "POST", u, nil)
	}
	if err != nil {
		return nil, err
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload string
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[string]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// GetUser performs GET /user.
func (c *Client) GetUser(
	ctx context.Context,
	headers http.Header,
) (*fetch.FetchResponse[User], error) {
	u := fmt.Sprintf("%s/user", c.BaseURL)
	req, err := http.NewRequestWithContext(ctx, "GET", u, nil)
	if err != nil {
		return nil, err
	}
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload User
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[User]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// DeanonymizeUser performs POST /user/deanonymize.
func (c *Client) DeanonymizeUser(
	ctx context.Context,
	body UserDeanonymizeRequest,
	headers http.Header,
) (*fetch.FetchResponse[OKResponse], error) {
	u := fmt.Sprintf("%s/user/deanonymize", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OKResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OKResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// ChangeUserEmail performs POST /user/email/change.
func (c *Client) ChangeUserEmail(
	ctx context.Context,
	body UserEmailChangeRequest,
	headers http.Header,
) (*fetch.FetchResponse[OKResponse], error) {
	u := fmt.Sprintf("%s/user/email/change", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OKResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OKResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// SendVerificationEmail performs POST /user/email/send-verification-email.
func (c *Client) SendVerificationEmail(
	ctx context.Context,
	body UserEmailSendVerificationEmailRequest,
	headers http.Header,
) (*fetch.FetchResponse[OKResponse], error) {
	u := fmt.Sprintf("%s/user/email/send-verification-email", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OKResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OKResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// VerifyChangeUserMFA performs POST /user/mfa.
func (c *Client) VerifyChangeUserMFA(
	ctx context.Context,
	body UserMFARequest,
	headers http.Header,
) (*fetch.FetchResponse[OKResponse], error) {
	u := fmt.Sprintf("%s/user/mfa", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OKResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OKResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// ChangeUserPassword performs POST /user/password.
func (c *Client) ChangeUserPassword(
	ctx context.Context,
	body UserPasswordRequest,
	headers http.Header,
) (*fetch.FetchResponse[OKResponse], error) {
	u := fmt.Sprintf("%s/user/password", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OKResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OKResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// SendPasswordResetEmail performs POST /user/password/reset.
func (c *Client) SendPasswordResetEmail(
	ctx context.Context,
	body UserPasswordResetRequest,
	headers http.Header,
) (*fetch.FetchResponse[OKResponse], error) {
	u := fmt.Sprintf("%s/user/password/reset", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OKResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OKResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// AddSecurityKey performs POST /user/webauthn/add.
func (c *Client) AddSecurityKey(
	ctx context.Context,
	headers http.Header,
) (*fetch.FetchResponse[PublicKeyCredentialCreationOptions], error) {
	u := fmt.Sprintf("%s/user/webauthn/add", c.BaseURL)
	req, err := http.NewRequestWithContext(ctx, "POST", u, nil)
	if err != nil {
		return nil, err
	}
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload PublicKeyCredentialCreationOptions
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[PublicKeyCredentialCreationOptions]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// VerifyAddSecurityKey performs POST /user/webauthn/verify.
func (c *Client) VerifyAddSecurityKey(
	ctx context.Context,
	body VerifyAddSecurityKeyRequest,
	headers http.Header,
) (*fetch.FetchResponse[VerifyAddSecurityKeyResponse], error) {
	u := fmt.Sprintf("%s/user/webauthn/verify", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload VerifyAddSecurityKeyResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[VerifyAddSecurityKeyResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// TokenExchange performs POST /token/exchange.
func (c *Client) TokenExchange(
	ctx context.Context,
	body TokenExchangeRequest,
	headers http.Header,
) (*fetch.FetchResponse[SessionPayload], error) {
	u := fmt.Sprintf("%s/token/exchange", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload SessionPayload
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[SessionPayload]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// VerifyTicketURL builds the URL for GET /verify without following the redirect.
func (c *Client) VerifyTicketURL(params *VerifyTicketParams,
) string {
	u := fmt.Sprintf("%s/verify", c.BaseURL)
	if params != nil {
		if q := params.toQuery(); len(q) > 0 {
			u += "?" + q.Encode()
		}
	}
	return u
}

// GetVersion performs GET /version.
func (c *Client) GetVersion(
	ctx context.Context,
	headers http.Header,
) (*fetch.FetchResponse[GetVersionResponse200], error) {
	u := fmt.Sprintf("%s/version", c.BaseURL)
	req, err := http.NewRequestWithContext(ctx, "GET", u, nil)
	if err != nil {
		return nil, err
	}
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload GetVersionResponse200
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[GetVersionResponse200]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// GetOpenIDConfiguration performs GET /.well-known/openid-configuration.
func (c *Client) GetOpenIDConfiguration(
	ctx context.Context,
	headers http.Header,
) (*fetch.FetchResponse[OAuth2DiscoveryResponse], error) {
	u := fmt.Sprintf("%s/.well-known/openid-configuration", c.BaseURL)
	req, err := http.NewRequestWithContext(ctx, "GET", u, nil)
	if err != nil {
		return nil, err
	}
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OAuth2DiscoveryResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OAuth2DiscoveryResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// GetOAuthAuthorizationServer performs GET /.well-known/oauth-authorization-server.
func (c *Client) GetOAuthAuthorizationServer(
	ctx context.Context,
	headers http.Header,
) (*fetch.FetchResponse[OAuth2DiscoveryResponse], error) {
	u := fmt.Sprintf("%s/.well-known/oauth-authorization-server", c.BaseURL)
	req, err := http.NewRequestWithContext(ctx, "GET", u, nil)
	if err != nil {
		return nil, err
	}
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OAuth2DiscoveryResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OAuth2DiscoveryResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// Oauth2AuthorizeURL builds the URL for GET /oauth2/authorize without following the redirect.
func (c *Client) Oauth2AuthorizeURL(params *Oauth2AuthorizeParams,
) string {
	u := fmt.Sprintf("%s/oauth2/authorize", c.BaseURL)
	if params != nil {
		if q := params.toQuery(); len(q) > 0 {
			u += "?" + q.Encode()
		}
	}
	return u
}

// Oauth2AuthorizePostURL builds the URL for POST /oauth2/authorize without following the redirect.
func (c *Client) Oauth2AuthorizePostURL() string {
	u := fmt.Sprintf("%s/oauth2/authorize", c.BaseURL)
	return u
}

// Oauth2Token performs POST /oauth2/token.
func (c *Client) Oauth2Token(
	ctx context.Context,
	body OAuth2TokenRequest,
	headers http.Header,
) (*fetch.FetchResponse[OAuth2TokenResponse], error) {
	u := fmt.Sprintf("%s/oauth2/token", c.BaseURL)
	form := url.Values{}
	form.Set("grant_type", fmt.Sprint(body.GrantType))
	if body.Code != nil {
		form.Set("code", fmt.Sprint(*body.Code))
	}
	if body.RedirectURI != nil {
		form.Set("redirect_uri", fmt.Sprint(*body.RedirectURI))
	}
	if body.ClientID != nil {
		form.Set("client_id", fmt.Sprint(*body.ClientID))
	}
	if body.ClientSecret != nil {
		form.Set("client_secret", fmt.Sprint(*body.ClientSecret))
	}
	if body.CodeVerifier != nil {
		form.Set("code_verifier", fmt.Sprint(*body.CodeVerifier))
	}
	if body.RefreshToken != nil {
		form.Set("refresh_token", fmt.Sprint(*body.RefreshToken))
	}
	if body.Resource != nil {
		form.Set("resource", fmt.Sprint(*body.Resource))
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewBufferString(form.Encode()))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OAuth2TokenResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OAuth2TokenResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// Oauth2UserinfoGet performs GET /oauth2/userinfo.
func (c *Client) Oauth2UserinfoGet(
	ctx context.Context,
	headers http.Header,
) (*fetch.FetchResponse[OAuth2UserinfoResponse], error) {
	u := fmt.Sprintf("%s/oauth2/userinfo", c.BaseURL)
	req, err := http.NewRequestWithContext(ctx, "GET", u, nil)
	if err != nil {
		return nil, err
	}
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OAuth2UserinfoResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OAuth2UserinfoResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// Oauth2UserinfoPost performs POST /oauth2/userinfo.
func (c *Client) Oauth2UserinfoPost(
	ctx context.Context,
	headers http.Header,
) (*fetch.FetchResponse[OAuth2UserinfoResponse], error) {
	u := fmt.Sprintf("%s/oauth2/userinfo", c.BaseURL)
	req, err := http.NewRequestWithContext(ctx, "POST", u, nil)
	if err != nil {
		return nil, err
	}
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OAuth2UserinfoResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OAuth2UserinfoResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// Oauth2Jwks performs GET /oauth2/jwks.
func (c *Client) Oauth2Jwks(
	ctx context.Context,
	headers http.Header,
) (*fetch.FetchResponse[OAuth2jwksResponse], error) {
	u := fmt.Sprintf("%s/oauth2/jwks", c.BaseURL)
	req, err := http.NewRequestWithContext(ctx, "GET", u, nil)
	if err != nil {
		return nil, err
	}
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OAuth2jwksResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OAuth2jwksResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// Oauth2Revoke performs POST /oauth2/revoke.
func (c *Client) Oauth2Revoke(
	ctx context.Context,
	body OAuth2RevokeRequest,
	headers http.Header,
) (*fetch.FetchResponse[json.RawMessage], error) {
	u := fmt.Sprintf("%s/oauth2/revoke", c.BaseURL)
	form := url.Values{}
	form.Set("token", fmt.Sprint(body.Token))
	if body.TokenTypeHint != nil {
		form.Set("token_type_hint", fmt.Sprint(*body.TokenTypeHint))
	}
	if body.ClientID != nil {
		form.Set("client_id", fmt.Sprint(*body.ClientID))
	}
	if body.ClientSecret != nil {
		form.Set("client_secret", fmt.Sprint(*body.ClientSecret))
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewBufferString(form.Encode()))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload json.RawMessage
	return &fetch.FetchResponse[json.RawMessage]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// Oauth2Introspect performs POST /oauth2/introspect.
func (c *Client) Oauth2Introspect(
	ctx context.Context,
	body OAuth2IntrospectRequest,
	headers http.Header,
) (*fetch.FetchResponse[OAuth2IntrospectResponse], error) {
	u := fmt.Sprintf("%s/oauth2/introspect", c.BaseURL)
	form := url.Values{}
	form.Set("token", fmt.Sprint(body.Token))
	if body.TokenTypeHint != nil {
		form.Set("token_type_hint", fmt.Sprint(*body.TokenTypeHint))
	}
	if body.ClientID != nil {
		form.Set("client_id", fmt.Sprint(*body.ClientID))
	}
	if body.ClientSecret != nil {
		form.Set("client_secret", fmt.Sprint(*body.ClientSecret))
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewBufferString(form.Encode()))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OAuth2IntrospectResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OAuth2IntrospectResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// Oauth2LoginGet performs GET /oauth2/login.
func (c *Client) Oauth2LoginGet(
	ctx context.Context,
	params *Oauth2LoginGetParams,
	headers http.Header,
) (*fetch.FetchResponse[OAuth2LoginResponse], error) {
	u := fmt.Sprintf("%s/oauth2/login", c.BaseURL)
	req, err := http.NewRequestWithContext(ctx, "GET", u, nil)
	if err != nil {
		return nil, err
	}
	if params != nil {
		req.URL.RawQuery = params.toQuery().Encode()
	}
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OAuth2LoginResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OAuth2LoginResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}

// Oauth2LoginPost performs POST /oauth2/login.
func (c *Client) Oauth2LoginPost(
	ctx context.Context,
	body OAuth2LoginRequest,
	headers http.Header,
) (*fetch.FetchResponse[OAuth2LoginCompleteResponse], error) {
	u := fmt.Sprintf("%s/oauth2/login", c.BaseURL)
	rawBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", u, bytes.NewReader(rawBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, vs := range headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}

	resp, err := c.fetch(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return nil, fetch.NewFetchErrorFromResponse(resp)
	}

	var payload OAuth2LoginCompleteResponse
	if err := fetch.DecodeJSON(resp, &payload); err != nil {
		return nil, err
	}
	return &fetch.FetchResponse[OAuth2LoginCompleteResponse]{Body: payload, Status: resp.StatusCode, Headers: resp.Header}, nil
}
