query GetJWTSecrets($appId: uuid!) {
  config(appID: $appId, resolve: false) {
    id: __typename
    __typename
    hasura {
      jwtSecrets {
        type
        key
        signingKey
        kid
        jwk_url
        allowed_skew
        audience
        claims_format
        claims_map {
          claim
          default
          path
          value
        }
        claims_namespace
        claims_namespace_path
        header
        issuer
      }
    }
  }
}
