query GetJWTSecrets($appId: uuid!) {
  config(appID: $appId, resolve: false) {
    id: __typename
    __typename
    hasura {
      jwtSecrets {
        type
        key
        signingKey
        kid
        jwk_url
      }
    }
  }
}
