// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nhost/nhost/services/ai/agents/tool (interfaces: Tool)
//
// Generated by this command:
//
//	mockgen -package mock -destination mock/tool.go github.com/nhost/nhost/services/ai/agents/tool Tool
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	slog "log/slog"
	reflect "reflect"

	provider "github.com/nhost/nhost/services/ai/agents/provider"
	gomock "go.uber.org/mock/gomock"
)

// MockTool is a mock of Tool interface.
type MockTool struct {
	ctrl     *gomock.Controller
	recorder *MockToolMockRecorder
	isgomock struct{}
}

// MockToolMockRecorder is the mock recorder for MockTool.
type MockToolMockRecorder struct {
	mock *MockTool
}

// NewMockTool creates a new mock instance.
func NewMockTool(ctrl *gomock.Controller) *MockTool {
	mock := &MockTool{ctrl: ctrl}
	mock.recorder = &MockToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTool) EXPECT() *MockToolMockRecorder {
	return m.recorder
}

// Definition mocks base method.
func (m *MockTool) Definition() provider.ToolDefinition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Definition")
	ret0, _ := ret[0].(provider.ToolDefinition)
	return ret0
}

// Definition indicates an expected call of Definition.
func (mr *MockToolMockRecorder) Definition() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Definition", reflect.TypeOf((*MockTool)(nil).Definition))
}

// Execute mocks base method.
func (m *MockTool) Execute(ctx context.Context, arguments string, logger *slog.Logger) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, arguments, logger)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockToolMockRecorder) Execute(ctx, arguments, logger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockTool)(nil).Execute), ctx, arguments, logger)
}
