---
name: "functions: release"
on:
  workflow_call:
    inputs:
      GIT_REF:
        required: true
        type: string
      VERSION:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        required: true
      NIX_CACHE_PUB_KEY:
        required: true
      NIX_CACHE_PRIV_KEY:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  # Node 22
  build_artifacts:
    uses: ./.github/workflows/wf_build_artifacts.yaml
    with:
      NAME: functions-node22
      PATH: services/functions
      GIT_REF: ${{ inputs.GIT_REF }}
      VERSION: ${{ inputs.VERSION }}
      DOCKER: true
      ENV: "NODE_VERSION=22"
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      NIX_CACHE_PUB_KEY: ${{ secrets.NIX_CACHE_PUB_KEY }}
      NIX_CACHE_PRIV_KEY: ${{ secrets.NIX_CACHE_PRIV_KEY }}

  push-docker-hub:
    uses: ./.github/workflows/wf_docker_push_image.yaml
    needs:
      - build_artifacts
    with:
      NAME: functions-node22
      PATH: services/functions
      VERSION: ${{ inputs.VERSION }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  push-docker-ecr:
    uses: ./.github/workflows/wf_docker_push_image_ecr.yaml
    needs:
      - build_artifacts
    with:
      NAME: functions-node22
      PATH: services/functions
      VERSION: ${{ inputs.VERSION }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      CONTAINER_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com

  # Node 20 variant
  build_artifacts_node20:
    uses: ./.github/workflows/wf_build_artifacts.yaml
    with:
      NAME: functions-node20
      PATH: services/functions
      GIT_REF: ${{ inputs.GIT_REF }}
      VERSION: ${{ inputs.VERSION }}
      DOCKER: true
      ENV: "NODE_VERSION=20"
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      NIX_CACHE_PUB_KEY: ${{ secrets.NIX_CACHE_PUB_KEY }}
      NIX_CACHE_PRIV_KEY: ${{ secrets.NIX_CACHE_PRIV_KEY }}

  push-docker-hub-node20:
    uses: ./.github/workflows/wf_docker_push_image.yaml
    needs:
      - build_artifacts_node20
    with:
      NAME: functions-node20
      PATH: services/functions
      VERSION: ${{ inputs.VERSION }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  push-docker-ecr-node20:
    uses: ./.github/workflows/wf_docker_push_image_ecr.yaml
    needs:
      - build_artifacts_node20
    with:
      NAME: functions-node20
      PATH: services/functions
      VERSION: ${{ inputs.VERSION }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      CONTAINER_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com
