---
name: "functions: release"
on:
  workflow_call:
    inputs:
      GIT_REF:
        required: true
        type: string
      VERSION:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        required: true
      NIX_CACHE_PUB_KEY:
        required: true
      NIX_CACHE_PRIV_KEY:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build_artifacts:
    strategy:
      matrix:
        node: ["20", "22"]
      fail-fast: true
    uses: ./.github/workflows/wf_build_artifacts.yaml
    with:
      NAME: functions
      PATH: services/functions
      GIT_REF: ${{ inputs.GIT_REF }}
      VERSION: ${{ inputs.VERSION }}
      DOCKER: true
      ENV: "NODE_VERSION=${{ matrix.node }}"
      ARTIFACT_SUFFIX: "-node${{ matrix.node }}"
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      NIX_CACHE_PUB_KEY: ${{ secrets.NIX_CACHE_PUB_KEY }}
      NIX_CACHE_PRIV_KEY: ${{ secrets.NIX_CACHE_PRIV_KEY }}

  push-docker-hub:
    strategy:
      matrix:
        node: ["20", "22"]
      fail-fast: true
    uses: ./.github/workflows/wf_docker_push_image.yaml
    needs:
      - build_artifacts
    with:
      NAME: functions
      PATH: services/functions
      VERSION: ${{ inputs.VERSION }}
      ENV: "NODE_VERSION=${{ matrix.node }}"
      ARTIFACT_SUFFIX: "-node${{ matrix.node }}"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
