---
name: "nhost-js: check changelog"
on:
  pull_request:
    paths:
      - '.github/workflows/wf_check_changelog.yaml'
      - '.github/workflows/nhost-js_checks.yaml'

      # common build
      - 'flake.nix'
      - 'flake.lock'
      - 'nix/**'
      - 'build/**'

      # common javascript
      - ".npmrc"
      - ".prettierignore"
      - ".prettierrc.js"
      - "audit-ci.jsonc"
      - "package.json"
      - "pnpm-workspace.yaml"
      - "pnpm-lock.yaml"
      - "turbo.json"

      # nhost-js
      - 'packages/nhost-js/**'

jobs:
  check-changelog:
    uses: ./.github/workflows/wf_check_changelog.yaml
    with:
      PROJECT_PATH: packages/nhost-js
